### ISSUE TITLE
CocoaPods version is old

### ISSUE THREAD

**Issue by kentya6** [thii/FontAwesome.swift#106]
Thanks for the awesome pod for the FontAwesome.

podspec version is 0.11.1, but CocoaPods version is 0.9.0.

Did you executed `pud trunk push` after [this](https://github.com/thii/FontAwesome.swift/commit/6362ea3310edf5895152696f6bab46ee5bdabbfd) commit?

**Comment by PVKonovalov** [comment]
I have the same behavior too. In my pod update log: 
... Using FontAwesome.swift (0.9.0) ..,

**Comment by chrisdhaan** [comment]
I'm experiencing the same problem. Would it be possible to push the new podspec?

**Comment by thii** [comment]
There is an issue in current CocoaPods which makes `pod trunk push` fails.
Please use the following for now:
`pod 'FontAwesome.swift', :git => 'https://github.com/thii/FontAwesome.swift', :tag => '0.11.1'`
