### ISSUE TITLE
Update to FontAwesome 4.6

### ISSUE THREAD

**Issue by arnaudlamy** [thii/FontAwesome.swift#108]
Need to update OTF library to 4.6. I can do it if nobody is working on it. I guess some has already started it no?

**Comment by thii** [comment]
Waiting for it. Please go ahead. Thanks in advance.

**Comment by arnaudlamy** [comment]
Done, merge requested.

**Comment by thii** [comment]
Looks like you opened 2 pull requests. Which one should I go with?

**Comment by arnaudlamy** [comment]
I did one for Swift 2.3 and one for Swift 3.0, isn't what to do ?

**Comment by tanujtak1986** [comment]
Hi Guys, Can you please merge this , so that it is available. Need the new instagram icon.

**Comment by tanujtak1986** [comment]
Thanks a log guys. Appreciate it.

**Comment by tanujtak1986** [comment]
Hi @thii ,

I updated pods, but i still cant see the new instagram icon. The the icon displayed is still the old one.
Can you please look into this. Appreciate the help.

**Comment by arnaudlamy** [comment]
You need to wait for a new release, or install it manually from sources.

**Comment by tanujtak1986** [comment]
Oh. Okay. Thanks.
