### ISSUE TITLE
Icon from array of icons?

### ISSUE THREAD

**Issue by RNUK** [thii/FontAwesome.swift#112]
I'm adding icons to a tableview and I have an array of the icons I want. I've setup a label in the cell and I want to run through the array and pick out the icon to display, but I keep getting a EXC_BAD_Instruction error. Any ideas?

My code is as follows:

(cell?.contentView.viewWithTag(1)! as! UILabel).text = String.fontAwesomeIconWithName(FontAwesome(rawValue: String(format: "%@", icons[(indexPath as NSIndexPath).row]))!)

Array defined as:
open var icons:[String] = ["Home", "User", "Folder", "Inbox", "Calendar", "MapMarker", "Search","Users", "Info","Bug", "SignOut"]

**Comment by OliverZiegler** [comment]
Your strings in your array are not the raw values for the FontAwesome Enum.

Have a look in [Enum.swift](https://github.com/thii/FontAwesome.swift/blob/master/FontAwesome/Enum.swift) to check for the raw values.

Why don't you already define the enum values in your array like this:
(current version: 0.11.1 and swift 3)

```swift
var icons:[FontAwesome] = [.home, .user, .inbox]
```
and so you can create your Icons like:
```swift
String.fontAwesomeIcon(name: icons[indexPath.row])
```
