### ISSUE TITLE
Swift 3 Build Error

### ISSUE THREAD

**Issue by Craytor** [thii/FontAwesome.swift#113]
I am receiving the following error when I try to build with Swift 3. Any ideas? Thanks!
<img width="787" alt="screen shot 2016-10-02 at 1 35 19 pm" src="https://cloud.githubusercontent.com/assets/3680866/19022375/31b265be-88a5-11e6-8e37-218cc7c8d386.png">

**Comment by jeffeom** [comment]
Just do what it says 😄 : Xcode > Edit > Convert > To Current Swift Syntax fixes it for now.
I hope dev work on this in the future so people do not have to do this manually.

**Comment by antonyalkmim** [comment]
The pod has not been updated, it is still v0.9.0 on CocoaPods. The podspec v0.11.1, compatible with swift3.0 was not pushed to CocoaPods.

Try this for now : 
```pod 'FontAwesome.swift', :git => 'https://github.com/thii/FontAwesome.swift.git', :branch => 'master'```

**Comment by Craytor** [comment]
Yes, when I had done what @antonyalkmim had said I get the above error. That's what I'm currently using in my Podfile.

**Comment by Craytor** [comment]
Never mind; updating cocapods to 1.1.0 fixed the issue.

**Comment by antonyalkmim** [comment]
Try this workaround

Select : Pods > FontAwesome.swift > Build Settings
Then set 'Use Legacy Swift Language Version' to 'NO'

![captura de tela 2016-10-03 as 21 34 12](https://cloud.githubusercontent.com/assets/6514332/19058860/45e15cf4-89b1-11e6-91a8-e6b4121f0ac0.png)


or you can use this in your Podfile:
````
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
```

**Comment by Craytor** [comment]
@antonyalkmim Updating cocapods to 1.1.0 fixed the issue.
