### ISSUE TITLE
Swift 3 Pod

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [thii/FontAwesome.swift#116]
What is to be write inside Podfile in order to download Font Awesome for Swift 3?

**Comment by Akisazaki** [comment]
maybe this will work (in my case): 

pod 'FontAwesome.swift', :git=>'https://github.com/thii/FontAwesome.swift.git'

**Comment by Rashesh-Bosamiya** [comment]
This works.

Thank you.

**Comment by OliverZiegler** [comment]
This still shows code changes and wants to convert syntax.
Code changes are the access level specifier.

With the `public` access level one prevents people from subclassing when using cocoapods.

See http://stackoverflow.com/a/38950955/2408916 for more information about changes and differences between `public`and `open`

**Comment by Fr0zenSide** [comment]
I can't use the last version of this framework directly with Swift 3 and cocoapods : 
`pod 'FontAwesome.swift', '~> 0.11.1'` 

Can you push the last podspec file on the cocoapods repo @thii ? 
The projet seems ready to be used with the last release (project is tagged in 0.11.1, podspec file is up to date but you need to send this file to the cocoapods spec repo :

```sh
echo "3.0" > .swift-version
pod trunk push FontAwesome.swift.podspec

# If you don't have session ready 
# You should see this error => [!] You need to register a session first. 
# Just execute : 
pod trunk register toto@gmail.fr "M. Toto" --description="Toto's Macbook Pro"
# check your email before to relaunch the push command
```

For now I use a static commit of your project but I have a lot of chance to miss the newest release : 
`pod 'FontAwesome.swift', :git => 'https://github.com/thii/FontAwesome.swift', :commit => 'b03d717'`

**Comment by philhudson91** [comment]
+1

**Comment by thii** [comment]
Please use `1.0.0`.
