### ISSUE TITLE
Xcode 8, Swift 3 - Older Version of the Compiler error

### ISSUE THREAD

**Issue by bbeckley** [thii/FontAwesome.swift#117]
Can we please get a version built with sdk 10.

Module file was created by an older version of the compiler; rebuild 'FontAwesome_swift' and try again:iphonesimulator/FontAwesome_swift.framework/Modules/FontAwesome_swift.swiftmodule/x86_64.swiftmodule

Xcode: Version 8.0 (8A218a)
Pod entry: pod 'FontAwesome.swift', :git=>'https://github.com/thii/FontAwesome.swift.git'

**Comment by doedje** [comment]
I had the same problem and the fix was (at least in my case) to [delete the contents of the DerivedData' folder](http://stackoverflow.com/questions/38016143/how-to-delete-derived-data-in-xcode-8)

**Comment by thii** [comment]
Please use `1.0.0`.
