### ISSUE TITLE
Failed to render and update auto layout status

### ISSUE THREAD

**Issue by gabrielrigon** [thii/FontAwesome.swift#118]
These erros appears only when build on storyboard screen. Can someone help me?

![captura de tela 2016-10-11 as 15 02 54](https://cloud.githubusercontent.com/assets/18755408/19282297/10010ba2-8fc4-11e6-9eaf-c175ba082887.png)

**Comment by strfn** [comment]
+1 can't get rid of this issue.

**Comment by mohsinka** [comment]
Any update on this? Please help. I am experiencing the same.

**Comment by OlafAndreas** [comment]
So this is an old issue getting no response and will be closed if we don't get any more details describing the errors you're experiencing.

You can check your build logs in `~/Library/Logs/DiagnosticReports`.
