### ISSUE TITLE
problem in run app

### ISSUE THREAD

**Issue by omidkh68** [thii/FontAwesome.swift#12]
hi, I have a problem, when I run the app, the compiler get an error in this line of fontAwesome.swift : "let data = NSData(contentsOfURL: fontURL!)!"

i think this error happen for link of font and class, isn't it?

**Comment by habitatus** [comment]
@omidkh68 Check out the second step in this post: http://codewithchris.com/common-mistakes-with-adding-custom-fonts-to-your-ios-app/#doublechecktarget

**Comment by omidkh68** [comment]
@habitatus  thank you so much,exactly this is my problem!

**Comment by krishaamer** [comment]
Thank you, I had this problem as well.

**Comment by thii** [comment]
In latest version (as of writing, 0.4.2), you don't need to do any extra step. It just works!
