### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kavoskhajavi** [thii/FontAwesome.swift#121]
error

Pods/FontAwesome.swift/FontAwesome/FontAwesome.swift:53:21: Value of type 'String' has no member 'substring'

FontAwesome.swift/FontAwesome/FontAwesomeView.swift:54:39: Type 'NSTextAlignment' has no member 'center'

**Comment by doedje** [comment]
migrate to swift3 when using master branch. Or use the swift-2.2 or swift-2.3 branch when you did not yet migrate to swift3...
