### ISSUE TITLE
UIImageView image size does not change.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [thii/FontAwesome.swift#130]
`var imgPlaceholder = UIImage.fontAwesomeIconWithName(.PictureO, textColor: UIColor.black.withAlphaComponent(0.5), size: CGSize(width: 20, height: 20))`

`self.imgView.image = imgPlaceholder`

Above code says, `imgPlaceholder` is UIImage size of `20 x 20` and `imgView` is UIImageView from `storyboard` which is size of `80 x 80`.

So, the problem is `imgPlaceholder` is growing as per the size of `imgView`. But I want to remain it to `20 x 20`.

Although imgView contentMode is `self.imgView.contentMode = .scaleAspectFit`.

How can I achieve it?

**Comment by thii** [comment]
You need to change the size of imgPlaceholder.
