### ISSUE TITLE
Does not compile using Swift 3.0.2

### ISSUE THREAD

**Issue by let-aurn** [thii/FontAwesome.swift#131]
Hi,

I just installed FontAwesome.swift using Cocoapod, but looks like it has not been upgraded to Swift 3.0.2 yet. Or is it?

Here is a piece of what Xcode complains about

FontAwesomeView.swift

<img width="1555" alt="capture d ecran 2017-03-27 a 19 48 08" src="https://cloud.githubusercontent.com/assets/13006409/24370113/79afc53a-1326-11e7-9b44-46af5780436d.png">

FontAwesome.swift

<img width="1560" alt="capture d ecran 2017-03-27 a 19 48 45" src="https://cloud.githubusercontent.com/assets/13006409/24370112/79aeb7e4-1326-11e7-9090-6c30881a31c4.png">

Thank you

**Comment by thii** [comment]
I haven't published v3.0.2 to CocoaPods yet. You can point your Podfile to this repo directly.

**Comment by thii** [comment]
It has been published now.
