### ISSUE TITLE
Button TitleView shows quesionmark

### ISSUE THREAD

**Issue by JaapWeijland** [thii/FontAwesome.swift#139]
I installed the pod with: 

`pod 'FontAwesome.swift', :git => 'https://github.com/thii/FontAwesome.swift'`

I'm importing:

`import FontAwesome_swift;`

...and I am setting the titleview. The 'cell.addButton' is a common UIButton:

`cell.addButton.setTitle(String.fontAwesomeIcon(name: FontAwesome.plus), for: .normal);
`

This is showing me a questionmark. I added FontAwesome.otf to the project and to my plist to be sure, but according to the documentation this shouldn't be necessary.

I'm using Swift 3.0 and I'm running the project with an iPhone SE.

**Comment by Maik639** [comment]
You have to update the font of the label. Setting the font will display the correct character. Keep in mind that every character is just an hex-code represented within an font. If that code doesn't exist, the character can not be represented.
See: https://developer.apple.com/reference/uikit/uilabel/1620532-font
