### ISSUE TITLE
No such module 'FontAwesome'

### ISSUE THREAD

**Issue by heyitswither** [thii/FontAwesome.swift#140]
I get the error' No such module FontAwesome' after both trying to install FontAwesome.swift with cocoapods and manually.

**Comment by nferruzzi** [comment]
import FontAwesome_swift

**Comment by heyitswither** [comment]
@nferruzzi 
> import FontAwesome_swift
yeah, i tried that and `import FontAwesome`

**Comment by thii** [comment]
@heyitswither It works for us though. Could you share a sample project which reproduces the error?

**Comment by heyitswither** [comment]
@thii i will get one in a few hours
