### ISSUE TITLE
Missing documentation in README on Storyboard support

### ISSUE THREAD

**Issue by anfriis** [thii/FontAwesome.swift#142]
I see in the recent commits that there is support for usage in Storyboards.

Could you provide som documentation in the README on how to use it?

**Comment by Maik639** [comment]
I added some documentation and an example project. Would be nice, if you have a look at it and leave feedback.

[https://github.com/thii/FontAwesome.swift/tree/feature/storyboard-support-documentation](url)

**Comment by cesarmtz93** [comment]
@anfriis any idea on how to use it with storyboards?

**Comment by anfriis** [comment]
Yeah the documentation and the example project is great.
Thank you!
