### ISSUE TITLE
Crash during runtime: `dyld: lazy symbol binding failed: Symbol not found`

### ISSUE THREAD

**Issue by anfriis** [thii/FontAwesome.swift#143]
I had version 1.1.2 installed using Carthage.
After updating to 1.2.0, the app compiles fine, but during runtime when executing `UIImage.fontAwesomeIcon(...` the app crashes with the following error:

dyld: lazy symbol binding failed: Symbol not found: __TIZFE11FontAwesomeCSo7UIImage15fontAwesomeIconFT4nameOS_11FontAwesome9textColorCSo7UIColor4sizeVSC6CGSize15backgroundColorS2_11borderWidthV12CoreGraphics7CGFloat11borderColorS2__S0_A2_
  Referenced from: /<redacted>/Application/B5CC41CF-617E-47E8-99B5-F53D53283DC2/<redacted>.app/<redacted>
  Expected in: /<redacted>/Application/B5CC41CF-617E-47E8-99B5-F53D53283DC2/<redacted>.app/Frameworks/FontAwesome.framework/FontAwesome

I then downgraded to 1.1.2 and it worked fine.
What could be wrong?

**Comment by thii** [comment]
You might not have added the framework correctly.

**Comment by anfriis** [comment]
Yeah but the point is that it works when downgrading to 1.1.2, so I guess it should also work using version 1.2.0.. Haven't changed the way the framework is added

**Comment by thii** [comment]
I could not reproduce the issue. Do you have a sample project which reproduce your issue?

**Comment by thii** [comment]
Close due to lack of response.
