### ISSUE TITLE
Swift 4 update?

### ISSUE THREAD

**Issue by 36bydesign** [thii/FontAwesome.swift#145]
Shouldn't take long, but I can't figure out how to get rid of this error:
"Cannot convert value of type '[String : Any].Type' to expected argument type '[String : Any]'.
#amateurlife

**Comment by thii** [comment]
@36bydesign Could you please explain in more details? A sample project would help a lot.

**Comment by doodzik** [comment]
I've encountered the same problem when updating to swift 4
