### ISSUE TITLE
XCODE9 issue carthage update  --no-use-binaries --platform iOS fails 

### ISSUE THREAD

**Issue by DKalachniuk** [thii/FontAwesome.swift#147]
Hi,
I'm using Xcode9 beta 1
call carthage update  --no-use-binaries --platform iOS

before that I did
xcode-select --print-path
sudo xcode-select --switch /Applications/Xcode-beta.app/Contents/Developer

I receive these errors in terminal

*** Building scheme "FontAwesome" in FontAwesome.xcodeproj
** BUILD FAILED **

The following build commands failed:
        CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
        CompileSwift normal armv7
(2 failures)
/Users/dkalachniuk/Projects/Umeter/Carthage/Checkouts/FontAwesome.swift/FontAwesome/FontAwesome.swift:155:47: error: val
ue of optional type 'CGFont?' not unwrapped; did you mean to use '!' or '?'?
A shell task (/usr/bin/xcrun xcodebuild -project /Users/dkalachniuk/Projects/Umeter/Carthage/Checkouts/FontAwesome.swift
/FontAwesome.xcodeproj -scheme FontAwesome -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_M
ODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
        CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
        CompileSwift normal armv7
(2 failures)

**Comment by mattdeckard** [comment]
Same issue using CocoaPods.

**Comment by thii** [comment]
This has been fixed in #146.
