### ISSUE TITLE
Compile time slowdown, and possible fix.

### ISSUE THREAD

**Issue by dsowsy** [thii/FontAwesome.swift#148]
I've been profiling one of my projects and noticed a slow compile time in Swift 4 with XCode 9. 
(-warn-long-function-bodies=100 in Swift other linker flags)

700ms in the function: 
```
fontAwesome(code: String)
```
By more explicitly setting the dictionary as: 
```
public let FontAwesomeIcons: Dictionary<String, String> = [
```
and
```
   public static func fontAwesome(code: String) -> FontAwesome? {
        if let name: String = FontAwesomeIcons[code]{
            return FontAwesome(rawValue: name)
        }
        return nil
    }

```
Brings the compile time down to less than 100ms.

**Comment by thii** [comment]
Thanks for your suggestion. I fixed it in ee6db527bec1c0494221a4e1f65073263c8ae97e.
