### ISSUE TITLE
Some icon cannot be made an image

### ISSUE THREAD

**Issue by haithngn** [thii/FontAwesome.swift#149]
Hi,

eg. .paw, .send, etc... cannot be make an image, they become question sign

```
let sendButton: UIButton = UIButton(type: .custom)
        sendButton.setImage(UIImage.fontAwesomeIcon(name: .sendO, textColor: .white,
                size: CGSize(width: 24, height: 24)), for: .normal)
        sendButton.addTarget(self, action: #selector(send), for: .touchUpInside)
        sendButton.frame = CGRect(x: 0, y: 0, width: 26, height: 26)

        let bearButton: UIButton = UIButton(type: .custom)
        bearButton.setImage(UIImage.fontAwesomeIcon(name: .plus, textColor: .white,
                size: CGSize(width: 24, height: 24)), for: .normal)
        bearButton.addTarget(self, action: #selector(sendWithBearTrack), for: .touchUpInside)
        bearButton.frame = CGRect(x: 36, y: 0, width: 26, height: 26)

        let composeBarButtonItem = UIBarButtonItem(customView: sendButton)
        let bearTrackBarButtonItem = UIBarButtonItem(customView: bearButton)
        navigationItem.rightBarButtonItems = [bearTrackBarButtonItem, composeBarButtonItem]
```

![screen shot 2017-06-21 at 11 19 41 am](https://user-images.githubusercontent.com/22902671/27366963-cf6084f2-5673-11e7-8a75-7f2c2c85e502.png)

**Comment by thii** [comment]
@haithngn Is that applied to all icons?Or just some icons above?

**Comment by haithngn** [comment]
@thii , I have not tried others icons yet

**Comment by thii** [comment]
@haithngn Could you try? If they all don't appear as icons, then there might be something wrong with your app.

**Comment by haithngn** [comment]
@thii I will try and report on Monday :)

**Comment by haithngn** [comment]
@thii ,
I have tried with another icons then here are the report

![screen shot 2017-06-26 at 10 25 20 am](https://user-images.githubusercontent.com/22902671/27523794-d61d3d6e-5a59-11e7-91ea-03a0f7ee1043.png)
![screen shot 2017-06-26 at 10 25 34 am](https://user-images.githubusercontent.com/22902671/27523796-d64506be-5a59-11e7-846a-02fb7ef582da.png)

**Comment by thii** [comment]
@haithngn It looks like the issue was with your custom bar buttons.

**Comment by haithngn** [comment]
@thii some icon like calendar, close, bell work ok.
I have tried with another Framework that has same problem with FontAwesome font.
Now, I have to use the Material font instead.

**Comment by haithngn** [comment]
thanks @thii

**Comment by bilawal-liaqat** [comment]
no icon working other than .github icon. 
Did anyone solve that issue?
