### ISSUE TITLE
This is not working on interface builder. I see a question mark. Any help?

### ISSUE THREAD

**Issue by patchthecode** [thii/FontAwesome.swift#154]
I dragged a UILabel unto storyBoard.
Then i changed the font to font awesome.
Then i pasted the icon -> 

It displays correctly on story board. But when i run the app, i am seeing a question mark.

Can you let me know the proper way to handle this on Interface builder/ Story board, with a UILabel?

**Comment by thii** [comment]
Probably the font was not loaded into memory before your storyboard was loaded. Do you have a sample project which reproduces this?

**Comment by james-ff** [comment]
For me this happens whenever the alpha of a previously working image changes or is set initally. See gif (buttons that turn to ? were clicked on which changes alpha by default) 
![2017-09-21 12 43 49](https://user-images.githubusercontent.com/1874352/30694223-feaa793a-9eca-11e7-841e-15c9c8a8e181.gif)

**Comment by james-ff** [comment]
`let barButtonItem = UIBarButtonItem.init(title: "", style: .plain, target: target, action: action)
        barButtonItem.setTitleTextAttributes([NSAttributedStringKey.font: UIFont.fontAwesome(ofSize: iconSize)], for: .normal)
        barButtonItem.title = "  \(String.fontAwesomeIcon(name: name))  "
        barButtonItem.tintColor = color
        return barButtonItem`

**Comment by electic** [comment]
I have the same problem. I ended up just making them images :( I am using 1.2.0

**Comment by james-ff** [comment]
@thii Is this a quick fix?

**Comment by thii** [comment]
I'll try to have a look at it sometime this weekend.

**Comment by Maik639** [comment]
Haven't tested it, but im pretty sure you have to set title text attributes for selected (and other) states too.
When selecting / pressing the button it changes to selected state and the title text attributes will be unset for that state.

**Comment by patchthecode** [comment]
yea.. maybe for a UIButton. But it doesnt work for a UILabel.

**Comment by phoney** [comment]
@james-ff @Maik639 This is a change in iOS 11 where setting textAttributes for themes or for controls requires setting the text attributes for both .normal and .highlighted.

**Comment by bradd-pktlzyer** [comment]
I had the same issue, shows in storyboard and ? in app. I walked the FontFamily and noticed font wasn't loading as I only used it in storyboard, I added a call to `UIFont.fontAwesome(ofSize: 16)` which installs the font via private FontLoad class. Worked after that.

**Comment by OlafAndreas** [comment]
Could someone confirm if in fact #170 provides a solution to this issue using: `UIFont.loadFontAwesome()` ?

**Comment by james-ff** [comment]
This has mostly been fixed by, as mentioned by @phoney applying attributes for multiple UIControlState enums, but the issue remains when a control is set to disabled (even though .disabled is used when setting the attributes).

```barButtonItem.setTitleTextAttributes([NSAttributedStringKey.font: UIFont.fontAwesome(ofSize: iconSize)], for: .normal)
        barButtonItem.setTitleTextAttributes([NSAttributedStringKey.font: UIFont.fontAwesome(ofSize: iconSize)], for: [.selected, .highlighted, .disabled, .reserved])```

**Comment by james-ff** [comment]
@thii 
Any progress on this issue?
To summarise my recent findings:
- Holding down on a bar button doesn't cause the ? mark effect
- Setting a bar button to disabled does
- This occurs despite setting all of the UIControlStates as in my last comment
- It seems that the UIControlStates addition fixes holding down, but not disabling a button
Many thanks for your hard work!

**Comment by OlafAndreas** [comment]
@james-ff 
Are you using `FontAwesomeBarButtonItem` as a custom `UIBarItem` ?
If not, you should try that. I managed to reproduce what you're describing by not using `FontAwesomeBarButtonItem` and fixed it by setting the custom `UIBarItem`.

**Comment by james-ff** [comment]
Could you provide sample code? I get the same outcome with the same setup of FontAwesomeBarButtonItem, and with just setting the title to cssCode I always get ?

**Comment by phoney** [comment]
@james-ff Can you setTitleTextAttributes for each of the states separately, without using the option set? That's how I've done it. 

When you tap on the barButtonItem, as shown in your video, the state of the barButtonItem changes to highlighted or selected, and apparently it doesn't know what to do in those cases.

**Comment by james-ff** [comment]
@phoney 
That worked! 
```swift
let titleTextAttributes = [NSAttributedStringKey.font: UIFont.fontAwesome(ofSize: iconSize)]
        barButtonItem.setTitleTextAttributes(titleTextAttributes, for: .normal)
        barButtonItem.setTitleTextAttributes(titleTextAttributes, for: .selected)
        barButtonItem.setTitleTextAttributes(titleTextAttributes, for: .highlighted)
        barButtonItem.setTitleTextAttributes(titleTextAttributes, for: .disabled)
```
It seems that setting UIControlStates as an array of options has issues, which is a shame because it means less dry code. Would this be an issue with swift or this library?
Many Thanks @phoney!

**Comment by phoney** [comment]
I think it's a UIKit issue and I think it's new in iOS 11. Neve filed a bug though. Before that you could set the theme for .normal and it applied to all the states. I think it worked that way since the beginning.

**Comment by alanscarpa** [comment]
This also displays a question mark instead of an icon when I assign this to the text of a UILabel `let phoneIconString = String.fontAwesomeIcon(name: .phone)`

**Comment by patchthecode** [comment]
closing this issue.
Apple released glyphs. I'll use those instead of a lib.
