### ISSUE TITLE
Deprecation warning on Xcode 9 GM with Swift 4

### ISSUE THREAD

**Issue by ghowen** [thii/FontAwesome.swift#157]
FontAwesome.swift:53:30: 'substring(to:)' is deprecated: Please use String slicing subscript with a 'partial range upto' operator.

**Comment by shuuja** [comment]
@ghowen did you use this pod in swift 4?
i am facing errors in this

**Comment by georgealegre** [comment]
@ghowen @shuuja There is a swift-4.0 branch. I'm using it with Cocoapods in my project and it works perfectly.

**Comment by ghowen** [comment]
@georgealegre Great, thanks. 
@shuuja Installing the pod from the source helped me to get the right version. So instead of
`pod 'FontAwesome.swift'`
you need
`pod 'FontAwesome.swift', :git => 'https://github.com/thii/FontAwesome.swift.git', :branch => 'swift-4.0'`
in your podfile.

**Comment by PascalMinder** [comment]
The build seems to be failing:
```
Carthage/Checkouts/FontAwesome.swift/FontAwesome/FontAwesome.swift:103:13: error: type 'NSAttributedStringKey' (aka 'NSString') has no member 'font'
            NSAttributedStringKey.font: UIFont.fontAwesome(ofSize: fontSize),
            ^~~~~~~~~~~~~~~~~~~~~ ~~~~
ObjectiveC.NSObject:160:15: note: did you mean 'zone'?
    open func zone() -> NSZone!
              ^
ObjectiveC.NSObject:162:21: note: did you mean 'zone'?
    open class func zone() -> NSZone!
                    ^
/Users/.../Documents/Projects/.../Carthage/Checkouts/FontAwesome.swift/FontAwesome/FontAwesome.swift:151:37: error: cannot force unwrap value of non-optional type 'CGFont'
            font = CGFont(provider!)!
                   ~~~~~~~~~~~~~~~~~^
                                    

** BUILD FAILED **


The following build commands failed:
        CompileSwift normal armv7k
        CompileSwiftSources normal armv7k com.apple.xcode.tools.swift.compiler
```

**Comment by thii** [comment]
@PascalMinder Which branch are you building from?

**Comment by PascalMinder** [comment]
I use the swift-4.0 branch.

**Comment by ghowen** [comment]
@PascalMinder Is the Swift version of the pod set to 4.0?
![image](https://user-images.githubusercontent.com/390784/30783243-5e41ccae-a137-11e7-942e-4fe42bb2250e.png)

**Comment by PascalMinder** [comment]
@ghowen No I haven't

**Comment by gangelo** [comment]
Compile errors using Carthage.

**Cartfile:**

# Font Awesome for Swift
github "thii/FontAwesome.swift"

**Errors:**

/Users/johndoe/dev/iOS/Accumoo/Carthage/Checkouts/FontAwesome.swift/FontAwesome/FontAwesome.swift:103:13: error: use of unresolved identifier 'NSAttributedStringKey'
            NSAttributedStringKey.font: UIFont.fontAwesome(ofSize: fontSize),
            ^~~~~~~~~~~~~~~~~~~~~
Foundation.NSAttributedString:2:12: note: did you mean 'NSAttributedString'?
open class NSAttributedString : NSObject, NSCopying, NSMutableCopying, NSSecureCoding {
           ^
<unknown>:0: note: did you mean 'CFAttributedStringRef'?
/Users/johndoe/dev/iOS/Accumoo/Carthage/Checkouts/FontAwesome.swift/FontAwesome/FontAwesome.swift:104:13: error: use of unresolved identifier 'NSAttributedStringKey'
            NSAttributedStringKey.foregroundColor: textColor,
            ^~~~~~~~~~~~~~~~~~~~~
Foundation.NSAttributedString:2:12: note: did you mean 'NSAttributedString'?
open class NSAttributedString : NSObject, NSCopying, NSMutableCopying, NSSecureCoding {
           ^
<unknown>:0: note: did you mean 'CFAttributedStringRef'?
/Users/johndoe/dev/iOS/Accumoo/Carthage/Checkouts/FontAwesome.swift/FontAwesome/FontAwesome.swift:105:13: error: use of unresolved identifier 'NSAttributedStringKey'
            NSAttributedStringKey.backgroundColor: backgroundColor,
            ^~~~~~~~~~~~~~~~~~~~~
Foundation.NSAttributedString:2:12: note: did you mean 'NSAttributedString'?
open class NSAttributedString : NSObject, NSCopying, NSMutableCopying, NSSecureCoding {
           ^
<unknown>:0: note: did you mean 'CFAttributedStringRef'?
/Users/johndoe/dev/iOS/Accumoo/Carthage/Checkouts/FontAwesome.swift/FontAwesome/FontAwesome.swift:106:13: error: use of unresolved identifier 'NSAttributedStringKey'
            NSAttributedStringKey.paragraphStyle: paragraph,
            ^~~~~~~~~~~~~~~~~~~~~
Foundation.NSAttributedString:2:12: note: did you mean 'NSAttributedString'?
open class NSAttributedString : NSObject, NSCopying, NSMutableCopying, NSSecureCoding {
           ^
<unknown>:0: note: did you mean 'CFAttributedStringRef'?
/Users/johndoe/dev/iOS/Accumoo/Carthage/Checkouts/FontAwesome.swift/FontAwesome/FontAwesome.swift:107:13: error: use of unresolved identifier 'NSAttributedStringKey'
            NSAttributedStringKey.strokeWidth: strokeWidth,
            ^~~~~~~~~~~~~~~~~~~~~
Foundation.NSAttributedString:2:12: note: did you mean 'NSAttributedString'?
open class NSAttributedString : NSObject, NSCopying, NSMutableCopying, NSSecureCoding {
           ^
<unknown>:0: note: did you mean 'CFAttributedStringRef'?
/Users/johndoe/dev/iOS/Accumoo/Carthage/Checkouts/FontAwesome.swift/FontAwesome/FontAwesome.swift:108:13: error: use of unresolved identifier 'NSAttributedStringKey'
            NSAttributedStringKey.strokeColor: borderColor
            ^~~~~~~~~~~~~~~~~~~~~
Foundation.NSAttributedString:2:12: note: did you mean 'NSAttributedString'?
open class NSAttributedString : NSObject, NSCopying, NSMutableCopying, NSSecureCoding {
           ^
<unknown>:0: note: did you mean 'CFAttributedStringRef'?

** BUILD FAILED **

The following build commands failed:
	CompileSwift normal armv7k
	CompileSwiftSources normal armv7k com.apple.xcode.tools.swift.compiler
(2 failures)
