### ISSUE TITLE
Bug when compiling with v0.3.0: you need to release the pod version 0.3.1 with its updates.

### ISSUE THREAD

**Issue by King-Wizard** [thii/FontAwesome.swift#16]
The API v0.3.0 does not compile with Xcode Version 6.3.2 (6D2105).

For fixing that, you should release as quick as possible the pod version 0.3.1 including these two commits below:

https://github.com/thii/FontAwesome.swift/commit/4972f69f83b349528e080fef1dc34bb5bfcd05aa

https://github.com/thii/FontAwesome.swift/commit/7ba3a833beb11b593bb420d41fd1c2dd241d5f26

Note: thank you for keeping me updated of this future release.

Thank you in advance.

**Comment by thii** [comment]
@King-Wizard Just released it.
