### ISSUE TITLE
Combination of icon + text -> text gets cutted

### ISSUE THREAD

**Issue by M-HERBRICH-ITC** [thii/FontAwesome.swift#166]
I'm using an font-awesome icon + some text string and e.g. the letter "g" gets cutted on the bottom.

![bildschirmfoto 2017-10-26 um 14 27 51](https://user-images.githubusercontent.com/4866997/32052986-1e6503f8-ba5a-11e7-8de1-cf63d7760e6b.png)
![bildschirmfoto 2017-10-26 um 14 28 03](https://user-images.githubusercontent.com/4866997/32052987-1e7e5fec-ba5a-11e7-9434-2c65c1ea773c.png)

My code for the login UIButton:
```
self.loginButton.titleLabel?.font = UIFont.fontAwesome(ofSize: 20)
self.loginButton.setTitle("Login " + String.fontAwesomeIcon(name: .arrowCircleRight), for: .normal)
```

Code for the logout BarButtonItem
```
let attributes = [NSAttributedStringKey.font: UIFont.fontAwesome(ofSize: 17)] as [NSAttributedStringKey: Any]
self.logoutButton.setTitleTextAttributes(attributes, for: .normal)
self.logoutButton.setTitleTextAttributes(attributes, for: .selected)
self.logoutButton.title = String.fontAwesomeIcon(name: .signOut) + " Logout"
```

**Comment by OlafAndreas** [comment]
This can be caused by the height of the button not making room for the titleLabel content. Can you make sure this isn't the case?

**Comment by M-HERBRICH-ITC** [comment]
@OlafAndreas 
Height is fine. Tested even much too big label and still occurs

**Comment by OlafAndreas** [comment]
I was able to reproduce the problem you're describing. 
One solution might be: 
1. Create a NSMutableAttributedString for the icon with FontAwesome font.
2. Create a NSAttributedString for the title with the font you want.
3. Append title string to icon string.
4. Set setAttributedTitle of button with the icon string.

Note: the fonts used should have the same size or else they will not align on the vertical axis. You could have different sizes but then you must calculate the difference between them and use that as a baselineOffset.

Please see if this covers your needs :)

**Comment by StefanDesu** [comment]
@OlafAndreas 
I just had the exact same issue as @M-HERBRICH-ITC, so I tried your solution and wanted to let you know that it worked perfectly! For anyone who likes to just copy and paste:

`let icon = NSMutableAttributedString(string: String.fontAwesomeIcon(name: .cog), attributes: [.font: UIFont.fontAwesome(ofSize: 17)])`
`let text = NSAttributedString(string: " Settings", attributes: [.font: UIFont.systemFont(ofSize: 17)])`
`icon.append(text)`
`settingsButton.setAttributedTitle(icon, for: .normal)`

**Comment by OlafAndreas** [comment]
I'm glad to hear it, maybe this is something that could be implemented into the framework.
@thii, what do you think?
