### ISSUE TITLE
Xcode 9.1 introduced 3 new compiler warnings

### ISSUE THREAD

**Issue by ghowen** [thii/FontAwesome.swift#167]
Pods/FontAwesome.swift/FontAwesome/FontAwesomeTextRepresentable.swift:25:40: Redundant layout constraint 'Self' : 'AnyObject'

Pods/FontAwesome.swift/FontAwesome/FontAwesome.swift:53:37: 'characters' is deprecated: Please use String or Substring directly

Pods/FontAwesome.swift/FontAwesome/FontAwesome.swift:54:51: 'characters' is deprecated: Please use String or Substring directly

**Comment by thii** [comment]
Thanks for reporting - want to submit a PR?

**Comment by ahmedsafadii** [comment]
Redundant layout constraint 'Self' : 'AnyObject'

**Comment by ahmedsafadii** [comment]
didn't fixed 'Redundant layout constraint 'Self' : 'AnyObject''

**Comment by thii** [comment]
@ahmedsafadii Do you want to submit a PR to fix it?

**Comment by OlafAndreas** [comment]
It is fixed in [this](https://github.com/thii/FontAwesome.swift/commit/bc4e0636e0b2dd888665c538c73bcf96fe8fc91b) commit, but the changes aren't released in a pod version yet.
