### ISSUE TITLE
FontAwesomeBarButtonItem.swift:49:40: Argument labels '(rawValue:)' do not match any available overloads

### ISSUE THREAD

**Issue by Fujikatoma** [thii/FontAwesome.swift#168]
I got this 3 errors. Using the newest Xcode and FontAwesome.swift version. Downloaded over cocoapod
 
/FontAwesome.swift/FontAwesome/FontAwesomeBarButtonItem.swift:49:40: Argument labels '(rawValue:)' do not match any available overloads

/FontAwesome.swift/FontAwesome/FontAwesomeBarButtonItem.swift:52:24: Type 'NSAttributedStringKey' (aka 'NSString') has no member 'font'

/FontAwesome.swift/FontAwesome/FontAwesomeBarButtonItem.swift:53:36: Cannot convert value of type '[NSAttributedStringKey : Any]' (aka 'Dictionary<NSString, Any>') to expected argument type '[String : Any]?'

**Comment by caseydedore** [comment]
Under similar circumstances I got this as well. For a temporary fix, I explicitly set the exact commit I want for FontAwesome in my podfile. I am using 1.2.2, but your needs may vary:

`pod 'FontAwesome.swift', :git => 'https://github.com/thii/FontAwesome.swift.git', :commit => '089b9acc35'`

**Comment by OlafAndreas** [comment]
This might be caused by the fact that the latest FontAwesome.swift uses Swift 4 and your Xcode environment is still using Swift 3.2, hence Xcode does not recognize the init overloads and the NSAttributedStringKey.font. Make sure you're using Swift 4 before using the latest FontAwesome version.

**Comment by OlafAndreas** [comment]
After no response from OP i think this issue should be closed for now. Please reopen or create a new issue if you need further assistance.
