### ISSUE TITLE
Stacking Icons

### ISSUE THREAD

**Issue by TrueV** [thii/FontAwesome.swift#178]
Is it possible to stack Icons, for example to indicate that there is _no wifi_ (**exclamation** on top of **wifi**) ?

**Comment by OlafAndreas** [comment]
There is no functionality for this within FontAwesome.

You can however achieve this by stacking two components of `UILabel` with the label on top having a transparent background.

Since this isn't really an issue with FontAwesome, I'm closing it.

**Comment by TrueV** [comment]
Thanks for the hint. 👍
