### ISSUE TITLE
In navigation item title?

### ISSUE THREAD

**Issue by miff** [thii/FontAwesome.swift#179]
Hi, 
Is there a way to this:
`navigationItem.title = "\(String.fontAwesomeIcon(name: .cube)) Some Text Here"`
![screen shot 2018-01-18 at 11 00 39](https://user-images.githubusercontent.com/469459/35092199-f137ed24-fc3e-11e7-986d-ae4e950551ae.png)

Thanks

**Comment by alanscarpa** [comment]
I'm having the same issue.  It seems to be specific to creating the icon as a string.  Ever find a workaround?

**Comment by OlafAndreas** [comment]
Maybe this suggestion to a previous issue is helpful: [#166 Combination of icon + text -> text gets cut](https://github.com/thii/FontAwesome.swift/issues/166#issuecomment-344856689)
