### ISSUE TITLE
Add support for Carthage

### ISSUE THREAD

**Issue by schickling** [thii/FontAwesome.swift#18]
It would be nice if this package could be installed via [Carthage](https://github.com/Carthage/Carthage). I don't like copy&pasting source code into my projects...

Keep up the good work!

**Comment by bjonica** [comment]
You don't need to copy and paste source code. If you use Cocoapods, you can just add "import FontAwesome_swift" to the top of your file. I'm not as familiar with Carthage to be know how to do the equivalent

**Comment by thii** [comment]
@schickling Yes, it can be installed via Carthage now.

**Comment by schickling** [comment]
Great! Thanks! :)
