### ISSUE TITLE
Text cutting from bottom

### ISSUE THREAD

**Issue by mrugeshtank** [thii/FontAwesome.swift#180]
I'm setting text to UIButton.
here is my code.
```
btnLogin.titleLabel?.font = UIFont.fontAwesome(ofSize: btnLogin.titleLabel!.font.pointSize)
btnSignup.titleLabel?.font = UIFont.fontAwesome(ofSize: btnSignup.titleLabel!.font.pointSize)
btnLogin.setTitle(String.fontAwesomeIcon(name: .signIn) + " " + Trans.shared.getTrans(ofNumber: 271) , for: .normal)
btnSignup.setTitle(String.fontAwesomeIcon(name: .user) + " " + Trans.shared.getTrans(ofNumber: 23) , for: .normal)
```
and I'm getting output as follow 
![screen shot 2018-03-03 at 4 12 51 pm](https://user-images.githubusercontent.com/11042449/36933425-5b8509aa-1efe-11e8-982b-31312dc7eaf1.png)

while without using fontAwesome Here is my code
```
btnLogin.setTitle(Trans.shared.getTrans(ofNumber: 271) , for: .normal)
btnSignup.setTitle(Trans.shared.getTrans(ofNumber: 23) , for: .normal)
```

and I'm getting output as follow
![screen shot 2018-03-03 at 4 11 38 pm](https://user-images.githubusercontent.com/11042449/36933441-91b78692-1efe-11e8-9fde-a1e27b243432.png)

Please help me to solve this issue

**Comment by thii** [comment]
It’s because the button titles also use the same font as the icons if you set like that.

**Comment by mrugeshtank** [comment]
then what should be suggested action ??

**Comment by thii** [comment]
The example is for icon-only button. You can use FontAwesome to create an image and assign it to your button using `setImage(_:for:)`:
https://developer.apple.com/documentation/uikit/uibutton/1623997-setimage

**Comment by mrugeshtank** [comment]
Thanks for help...
