### ISSUE TITLE
Doesn't seem to compile on 1.3.2

### ISSUE THREAD

**Issue by nickdnk** [thii/FontAwesome.swift#181]
I just updated to 1.3.2, and I have loads of compile errors inside the Pod framework.

Such as

`/Pods/FontAwesome.swift/FontAwesome/FontAwesomeBarButtonItem.swift:49:40: Argument labels '(rawValue:)' do not match any available overloads`

`/Pods/FontAwesome.swift/FontAwesome/FontAwesomeBarButtonItem.swift:53:36: Cannot convert value of type '[NSAttributedStringKey : Any]' (aka 'Dictionary<NSString, Any>') to expected argument type '[String : Any]?'`

What's going on? I tried Swift 3.2 and Swift 4 - same problem.

**Comment by aduval** [comment]
I got the exact same issue and fixed it. I switched my project to Swift 4 (Build Settings-> Swift Language Version) and did a complete pod cleanup (https://stackoverflow.com/questions/46428752/how-to-clear-or-clean-specific-pod-cache)
