### ISSUE TITLE
UIImage.fontAwesomeIconWithName not working

### ISSUE THREAD

**Issue by Boidkan** [thii/FontAwesome.swift#20]
With this code I get "could not find member .MapMarker"
`UIImage.fontAwesomeIconWithName(.MapMarker, textColor: UIColor.grayColor(), size: 20)`

With this code I get "cannot invoke 'fontAwesomeIconWithName' with and argument list of type '(FontAwesome,UIColor,Int)'
`            UIImage.fontAwesomeIconWithName(.MapMarker as FontAwesome, textColor: UIColor.grayColor(), size: 20)`

However I have no problem using
`String.fontAwesomeIconWithName(.MapMarker)`

Is this just me or is this a bug?

**Comment by thii** [comment]
@Boidkan Are you using CocoaPods or Carthage?

**Comment by thii** [comment]
@Boidkan Your code was incorrect. Please use this:

```swift
UIImage.fontAwesomeIconWithName(.MapMarker as FontAwesome, textColor: UIColor.grayColor(), size: CGSizeMake(20, 20))
```

**Comment by Boidkan** [comment]
Oh, my apologies for not looking at the input properly.
