### ISSUE TITLE
Icons also being loaded from view string literal values

### ISSUE THREAD

**Issue by geoherna** [thii/FontAwesome.swift#201]
Hi,

Having a strange issue where the string literal value of a UITextField is being interpreted as icon codes and rendered as the icons themselves.

Example Code: 

```
    func updateSpecificLocationField() {
        let carIcon = String.fontAwesomeIcon(name: .car)
        let placeholder = "Getting Location..."
        specificLocTxt.font = UIFont.fontAwesome(ofSize: 15, style: .solid)
        specificLocTxt.text = "\(carIcon) \(placeholder)"
    }
```

And the car icon works fine, but for the word "Location", I am literally getting a cat icon as well due to the "cat" lol:

![image](https://user-images.githubusercontent.com/5247153/57976389-a91b8680-79ac-11e9-9604-869c772318fd.png)

Edit: Apologies, forgot to add system specifics:

Xcode: 10.2.1
Swift 5
github "thii/FontAwesome.swift" "1.7.0" (via Carthage)

Also seeing the same issue w/ `UILabel`

**Comment by geoherna** [comment]
Also seeing the same issue w/ `UILabel`

**Comment by bitops** [comment]
I am seeing this same behavior as well. It seems that interpolation is having some unintended side effect.

**Comment by thii** [comment]
Could you attach a reproducible example project?

**Comment by geoherna** [comment]
@thii Yes, of course: 
[TestFA.zip](https://github.com/thii/FontAwesome.swift/files/3239363/TestFA.zip)

**Comment by geoherna** [comment]
Was this ever resolved? I provided the examples as requested.

**Comment by geoherna** [comment]
Bump

**Comment by doedje** [comment]
This is just my 5 cents, not thii's opinion: But isn't this a side-effect because you are displaying regular text using fontAwesome, it is supposed to display icons, not regular text.
