### ISSUE TITLE
Icon enum values point to the wrong icons

### ISSUE THREAD

**Issue by whoyawn** [thii/FontAwesome.swift#208]
<img width="97" alt="image" src="https://user-images.githubusercontent.com/15709918/58601058-0381d600-823c-11e9-830b-60bd35d25c42.png">
icons: `.times`

<img width="194" alt="image" src="https://user-images.githubusercontent.com/15709918/58601068-0bda1100-823c-11e9-84e9-68bb956f3eb8.png">

icons: `.inbox`, `.user`

Device: iPhone XR Simulator
Xcode 10.1
Swift 4.2

**Comment by thii** [comment]
Thanks for reporting. Mind submitting a PR to fix it?

**Comment by whoyawn** [comment]
For now, the workaround would be to upgrade to FontAwesome Swift 5 and use Xcode 10.2
