### ISSUE TITLE
How to use with Pro fonts?

### ISSUE THREAD

**Issue by svastven** [thii/FontAwesome.swift#209]
I have Pro font awesome but I can not figure out how to use it with this library. In my app delegate I set usesProFonts to true, but I see no change, the font names are still being fetched from the predefined dictionary. I need to use the fontAwesomeIcon(code: "fa-...") function, but with no luck. Is there a way?

Thanks!

**Comment by LukasHromadnik** [comment]
Hi :)

According to the documentation

```
/// Whether Font Awesome Pro fonts should be used (not included).
///
/// To use Font Awesome Pro fonts, you should add these to your main project and
/// make sure they are added to the target and are included in the Info.plist file.
public static var usesProFonts: Bool = false
```
did you add Pro fonts to the project?

**Comment by svastven** [comment]
I did add them to the project, and also to Info.plist file. They are named exactly like stated in the UIFont extension. However when I went through the FontAwesome.swift code I could not find any support for the Pro fonts.

**Comment by svastven** [comment]
I think that the use of the CSS codes like "fa-500px" is not supported. It is not possible to retrieve the icon in other way than the unicode character. But I found out that I also got some .json with the pro fonts so I'am probably going to parse my own dictionary and use it that way. 

Thanks anyways!! :)

**Comment by o15a3d4l11s2** [comment]
I believe pro fonts are not working, because it tries to load the font from FontAwesome's bundle, not the main application bundle, where the pro fonts are added:

```
extension URL {
    static func fontURL(for fontName: String) -> URL? {
        let bundle = Bundle(for: FontLoader.self)

        if let fontURL = bundle.url(forResource: fontName, withExtension: "otf") {
            return fontURL
        }

        // If this framework is added using CocoaPods, resources is placed under a subdirectory
        if let fontURL = bundle.url(forResource: fontName, withExtension: "otf", subdirectory: "FontAwesome.swift.bundle") {
            return fontURL
        }

        return nil
    }
}
```

**Comment by thii** [comment]
Yeah you need to replace the bundled fonts in FontAwesome's bundle with your pro fonts.

**Comment by o15a3d4l11s2** [comment]
@thii , thanks for the hint. I am using the library as a pod. What should be done in this case, so that we can add the pro fonts and not worry about updating the library will wipe out the changes?

**Comment by thii** [comment]
I would recommend adding a script after your pod install script to replace the font files every you run pod install. You should probably only replace with the same version of the pro fonts.

**Comment by ipodishima** [comment]
@o15a3d4l11s2 is it working for you?

**Comment by o15a3d4l11s2** [comment]
@ipodishima, at the end I decided to skip the library and just use the font. But I believe what @thii suggested should work properly.

**Comment by MoElnaggar14** [comment]
@o15a3d4l11s2 is it working?
