### ISSUE TITLE
No Such Module 'FontAwesome' in Swift Project

### ISSUE THREAD

**Issue by Sunnyztj** [thii/FontAwesome.swift#21]
Hello,

 I follow the installation guide:
1. Add  pod 'FontAwesome.swift' and run 'pod install'
2. Add 'import FontAwesome' to the controller file

After that I did import FontAwesome in my viewcontroller, then Xcode gave me No such module 'FontAwesome' error message. Please help me :)

p.s. I use Xcode 6.3.2

**Comment by thejourneydude** [comment]
Having the same issue as well. Any help on this would be appreciated.

**Comment by thii** [comment]
There is a problem with integrating this framework using CocoaPods right now. Please integrate it using Carthage or do it manually. I'll fix this soon.

**Comment by thii** [comment]
@Sunnyztj @thejourneydude Fixed!
Please use `import FontAwesome_swift` if you are using CocoaPods

**Comment by PanamaDonne** [comment]
Can get FontAwesome_swift to work. Same error as above.

**Comment by leizard** [comment]
import FontAwesome_swift currently doesn't work for me

**Comment by RolandasRazma** [comment]
same error

**Comment by xiandong79** [comment]
same error
