### ISSUE TITLE
Off by 1 in 1.7.1

### ISSUE THREAD

**Issue by ArdentZeal** [thii/FontAwesome.swift#210]
Hey,

if I pick .ring, I get .road.
If I pick .road, I get .robot.

So the enums are off by 1.

This does only happen in 1.7.1, I reverted to 1.7.0 and it is ok there.

Installed via Cocoapods.

Cheers

**Comment by thii** [comment]
Mind opening a PR to fix it?

**Comment by LukasHromadnik** [comment]
Hi.

I've just tested your case and I'm not able to reproduce this situation.

Do you mind providing some code?

**Comment by ArdentZeal** [comment]
Hey,

sorry for not replying before, but I am not able to do a PR at the moment due to time constraints.

Here is one of the lines, which caused the problem with 1.7.1

UIImage.fontAwesomeIcon(name: .road, style: .solid, textColor: UIColor.white, size: CLTableOverlayView.mIconSize) 

To reiterate, this one gives me the right one in 1.7.0, and one off in 1.7.1. At the moment I am running with 1.7.0 to ensure everything works, but if u can not reproduce the problem I can try to upgrade to 1.7.1 once more to double check.

**Comment by LukasHromadnik** [comment]
Still unable to reproduce. This is what I see
![Simulator Screen Shot - iPhone Xs - 2019-06-29 at 11 56 54](https://user-images.githubusercontent.com/2185200/60382581-5df19a80-9a65-11e9-94a8-7083e9db57d0.png)

**Comment by ArdentZeal** [comment]
Hey, thanks for the effort. I double-checked again and could not reproduce the issue either.
I use FontAwesome.swift in several targets, maybe I updated not all of them and got a missmatch? Just guessing at that point.

Well it is gone now, so everything seems to be fine. Thanks again :)
