### ISSUE TITLE
Question mark showing instead of picture

### ISSUE THREAD

**Issue by albarq** [thii/FontAwesome.swift#214]
Hi,

I have download the app and  it is working perfectly as shown in example folder, but once I tried to run at my project, my app doesn't recognise font..

I tried many solutions like:
- define in plist these font ... ending with ttf and otf 
- install this library manually and pod 'FontAwesomeKit.Swift'

There is something missing at my end but I don't what is ... 

could any one help me by giving me a clue :) 

Note: I searched a lot and find many other developer complain same issue with fontAwesome, but all that solution did work for me.

Thank you .

**Comment by LukasHromadnik** [comment]
Hi,

can you please provide us with some example of your code? I just tried new project with one label and it worked.

1) Did you set correct font?
2) This library is `FontAwesome.swift`, not `FontAwesomeKit.swift`. Maybe you have a problem with different library.

**Comment by albarq** [comment]
Thanks a lot my friend ...

I wrote for you long description to show you all steps that I am doing and showing me question mark, but for no reason it shows me the icon :) .. very strange ...

So god bless you ... you are my hero
