### ISSUE TITLE
crash on FontAwsome file loading

### ISSUE THREAD

**Issue by imranali123** [thii/FontAwesome.swift#22]
I added the FontAswome in swift using cocoa pods.
In file FontAwsome.swift on line no 29
let fontURL = bundle.URLForResource(name, withExtension: "otf")
fontURL is always nil, thats why application is crashing.

**Comment by thii** [comment]
@imranali123 It looks like you are using an earlier version of `FontAwesome.swift`. Please run `pod update` to update this framework to its latest version.

**Comment by imranali123** [comment]
i just added the FontAswome project 1 hour ago. I also tried to update the project. But still same issue.

**Comment by thii** [comment]
@imranali123 Which version are you using? Can you send in your `Podfile.lock` file?

**Comment by imranali123** [comment]
here is the podfile.lock entry
  - FontAwesome.swift (0.4.1)

**Comment by thii** [comment]
@imranali123 Could you please run `pod update` again? The latest version is 0.4.2.

**Comment by imranali123** [comment]
I tried pod update 3 to 4 time, but cocoa pods are fetching 0.4.1.
I tried to update pods by adding version by myself, than I am facing error. Because pods not recognising the version 0.4.2

**Comment by thii** [comment]
@imranali123 I just tried with a test project and had no issue fetching v0.4.2. You'll probably want try to remove this pod, run an update, add this pod and run an update again to see if it works.

**Comment by imranali123** [comment]
Thanks, this solved my problem
