### ISSUE TITLE
Error when using icons

### ISSUE THREAD

**Issue by pausanchezv** [thii/FontAwesome.swift#220]
Hello, after installing the module using cocoa pods and once the FontAwesome_swift package  has been imported, no errors are shown but I'm getting a question mark, instead of the item itself, every time I add a new icon.

Does anyone know what happens?

Thanks.

**Comment by LukasHromadnik** [comment]
Hello :)

Do you mind sharing some code with us?

In my experience the question mark indicates that the font is not set. See [Examples section](https://github.com/thii/FontAwesome.swift#examples)

**Comment by 5fcgdaeb** [comment]
Same problem here! Questions marks everywhere :)

@LukasHromadnik: I am using the library as specified in the Examples section.

XCode: 10.2
Swift: 5.0
macOS: 10.14.5 (Mojave)

I will dig deeper now since I have to solve this. I do have the 3 `otf` files under the Pods/FontAwesome.swift directory.

**Comment by 5fcgdaeb** [comment]
Here is a bit more information on the issue:

`label.text = String.fontAwesomeIcon(name: .check)`
```
(lldb) po label.text
▿ Optional<String>
  - some : ""
```

The output shows a question mark.

**Comment by 5fcgdaeb** [comment]
OK, figured things out! 

I upgraded from an older version to `1.8.1` and I guess certain icons require a pro membership now. For those, you get the question mark. The free stuff you can still use. There are no indicators though of what is free and not. If you try to use a pro icon, you will get the question mark.

Gallery at https://fontawesome.com/icons?d=gallery helps a lot to see which ones are pro and which ones are free. Picking the free ones render the icons correctly.

The signature change in the library to `UIFont.fontAwesome(ofSize: 17.0, style: .solid)` probably is the indicator. Before, you didn't have to provide a style.

Hope this helps someone else!

**Comment by yasingh7** [comment]
I'm using free icons and still get question mark. Is this because i use Interface Builder?

**Comment by braandl** [comment]
Is there any way to find out if an icon is free? Icons that used to work are gone after upgrade.

**Comment by braandl** [comment]
This Issue is not solved, tough. That you can not see what icons are from the free-Set and wich are not is a major drawback.

**Comment by JoNilsson** [comment]
@thii Any progress on this?

**Comment by siddharth-prajapati** [comment]
Try changing .style attribute from "brand" to something else that worked for me for bell icon

**Comment by liamse** [comment]
When you search your icon on [fontawesome.com](https://fontawesome.com/icons/) click on icon that you want. In its URL you will see its style. For example for **camera** icon it will be like this:  ../icons/camera?**style=solid**
You can use set it in your code like this:
```swift 
let attrString = NSMutableAttributedString(
            string: String.fontAwesomeIcon(name: .camera),
             attributes: [ .font: UIFont.fontAwesome(ofSize: size, style: .solid)]) // if you use .brands as its style, it will show ? icon
your_label.attributedText = attrString
```
