### ISSUE TITLE
Crash when used imported as Swift Package

### ISSUE THREAD

**Issue by valexa** [thii/FontAwesome.swift#236]
Adding to Xcode 11 as a swift package works fine however its crashes when trying to load the font files with : Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /.../SourcePackages/checkouts/FontAwesome.swift/FontAwesome/FontAwesome.swift, line 98

<img width="1424" alt="Screenshot 2019-10-21 at 10 28 22" src="https://user-images.githubusercontent.com/108781/67193826-dce05980-f3ed-11e9-8ee5-7e018265be94.png">

It look like the reason this happens is that Swift packages don't have Bundles so the font from the package can not be loaded, just copying "Font Awesome 5 Free-Solid-400.otf" into my project fixed the error.

**Comment by matt-matt1** [comment]
same problem
