### ISSUE TITLE
Compile Error: Cannot load underlying module for 'FontAwesome_swift'

### ISSUE THREAD

**Issue by JonathanGrant** [thii/FontAwesome.swift#24]
Hello,

I just finished my pod install of FontAwesome.swift with the exact podfile code you provided. My project is entirely empty. When I wrote "import FontAwesome" or "import FontAwesome_swift" into my ViewController.swift, I got this error.

How can I fix this?

**Comment by JonathanGrant** [comment]
Fixed:

Click Product:BuildFor:Testing

**Comment by tochi** [comment]
:+1:
