### ISSUE TITLE
New maintainer wanted

### ISSUE THREAD

**Issue by thii** [thii/FontAwesome.swift#251]
Please let me know if anyone wants to take over this project.

**Comment by valexa** [comment]
Hello, i'm using this library in a couple projects where I have to manually fix things so could give maintaining it a go.

**Comment by MatrixSenpai** [comment]
I'm willing to take over the maintaining of the package

**Comment by thii** [comment]
@valexa Thanks for your interest. We're expecting someone who have contributed to the project—including reporting/discussing issues and contributing code. We would love to have your contribution!

@MatrixSenpai Added you as a collaborator. Do you have a CocoaPods account? If you have any question about the release process, feel free to ask me via email.

**Comment by MatrixSenpai** [comment]
I do, it's the same as listed on my profile. My CP profile is [here](https://cocoapods.org/owners/9977)

**Comment by thii** [comment]
@MatrixSenpai Added you as a maintainer.
