### ISSUE TITLE
UINavigationItem icon not appearing

### ISSUE THREAD

**Issue by Daemon-Devarshi** [thii/FontAwesome.swift#254]
I am using following code to display an icon:

```
@IBOutlet weak var navigationTitle: UINavigationItem!

override func viewDidLoad() {
        super.viewDidLoad()

        let attributes = [NSAttributedString.Key.font: UIFont.fontAwesome(ofSize: 18, style: .regular)]
        drawerMenuItem.setTitleTextAttributes(attributes, for: .normal)
        drawerMenuItem.title = String.fontAwesomeIcon(name: .github)
}
```

But for some reasons it is not showing the icon but a question mark in place:

![Screenshot 2020-04-30 at 10 32 05 PM](https://user-images.githubusercontent.com/959126/80738171-327e8700-8b32-11ea-8a75-5ef34ef6b0f8.png)

Am I missing anything over here?

**Comment by MatrixSenpai** [comment]
Don't tie your navigation item to an `IBOutlet` as it is completely useless and there is no reason to re-implement it. Doing so could cause unexpected behavior. I repeat again, _do not re-implement `navigationItem` or any of its children_. _Always_ use their built in accessors via `self.navigationItem`

You should instead use the member `leftBarButtonItem`.

Try this code sample instead:
```swift
var leftButton: UIBarButtonItem {
  let b = UIBarButtonItem(title: String.fontAwesomeIcon(name: .github), style: .plain, target: <#T##Any?#>, action: <#T##Selector?#>)
  b.setTitleTextAttributes([.font: UIFont.fontAwesome(ofSize: 18, style: .regular)], for: .normal)
  b.setTitleTextAttributes([.font: UIFont.fontAwesome(ofSize: 18, style: .solid)], for: .highlighted)
  return b
}

override func viewDidLoad() {
  super.viewDidLoad()

  navigationItem.leftBarButtonItem = leftButton
}
```

Do note that the placeholders left in the `UIBarButtonItem` initializer are left there for your convenience. Fill them in with the actions supplied to your button.

You should also set text attributes for `.normal` as well as `.highlighted`. Failure to do so will give you the unknown unicode icon when your bar button is tapped

**Comment by Daemon-Devarshi** [comment]
@MatrixSenpai your code did not fix the issue for me either. I will try to create a separate project, and share it here.

Also seems like the point which you overemphasised is not accurate. The apple documentation link which you pointed does not validate it. Also on doing a quick google search noticed a related code from an O'Reilly book, please have a look:

![Screenshot 2020-05-02 at 10 20 57 AM](https://user-images.githubusercontent.com/959126/80855412-a7e77600-8c5e-11ea-8ab1-b159ea699d41.png)

As a matter of fact you are creating a separate barButtonItem and assigning it programmatically to leftBarButtonItem property, the same thing which I did through storyboard.

**Comment by Daemon-Devarshi** [comment]
@MatrixSenpai the solution which you proposed did not work for me either. 

Having said that I am able to find the solution. Posting here so that it in future it may help someone who faces same problem:
 
Looks like the display of font awesome icon on UIBarButtonItem depends upon the style. For example in my case I was using the style as regular for GitHub icon, however I got it working by using the style as brands. In other cases it can be different, as an example if I am using bars icons then it is displayed only if the style is solid.

Also the point which you overemphasised is flawed. Neither there is any relevant content justifying it in the Apple Documentation which you referenced. As a matter of fact you are also creating a separate instance of UIBarButtonItem, programmatically, which I did through storyboard. I googling noticed that this practise not very uncommon:

- https://riptutorial.com/ios/example/13626/creating-a-uibarbuttonitem-in-the-interface-builder
- https://stackoverflow.com/a/30081140/217586

**Comment by MatrixSenpai** [comment]
Ah, seems I missed which icon you were using. You're correct, the font you were using was incorrect, and checking that is very important :) _Brands_ font includes the GitHub icon, while the code you posted has you using the _regular_ font, an important distinction.

I should rephrase my earlier advice, since it seems you've edited your code. Referencing a bar button item is, while redundant, safe to do. However, referencing a nav item is unsafe. The best and safest practice is simply to use the built-in accessor already included in `UIViewController`

**Comment by Daemon-Devarshi** [comment]
Understood, I see where the confusion was.
