### ISSUE TITLE
Use from unicode char?

### ISSUE THREAD

**Issue by beloso** [thii/FontAwesome.swift#255]
It used to be possible to use the icons from a unicode character

Could we recover that functionality?

**Comment by MatrixSenpai** [comment]
you still can. just make sure you're using the unicode properly
```swift
// make sure to replace the contents of the curly braces with the icon you would like to use
myLabel.text = "\u{f0ac}" 
```

**Comment by beloso** [comment]
How about for images?

My main problem is with generating an image from a Unicode char.

**Comment by MatrixSenpai** [comment]
Is there a particular reason you _have_ to use unicode? The API has two features that may be more useful. Each FontAwesome icon has a `rawValue: String` property, that matches the CSS codes for each particular icon. The second is `UIImage.fontAwesomeIcon(code: String, style: textColor: size:)` that allows you to create a FontAwesome image from a CSS code. If you need to store and retrieve these codes, you can do something like this
```swift
let toStorage: String = icon.rawValue // icon being an instance of FontAwesome
store(toStorage, "identifier")
...
let fromStorage: String = retrieve("identifier")
let image = UIImage.fontAwesomeIcon(code: fromStorage, style: .regular, textColor: .black, size: CGSize(width: 10, height: 10))
```

**Comment by beloso** [comment]
Well I am using a REST API that I don't own. They are sending the icon as a unicode char.
If you'd ask me I'd prefer using the CSS name. But in this case I don't have an option.

**Comment by MatrixSenpai** [comment]
Since this is coming from an API, this may warrant further investigation. However, for the time being, here's a solution that may work
```swift
let icon = resultFromApi.icon
// Here we will leverage the CaseIterable conformity of the FontAwesome enum
// Take note, if ONLY the unicode char is returned, and not the enclosing \u{}, you may need to
// interpolate the icon variable inside of a string, as in "\u{\(icon)}"
// Also note that in case the icon unicode is not found, you can provide a default. 
// The `first` property will be optional
let fa = FontAwesome.allCases.filter { $0.unicode == icon }.first ?? FontAwesome.question
```

**Comment by beloso** [comment]
Thank you, your suggestion does help me out.

One thing though, it's not enough to do `\u{\(code)}`. The compiler cries.
I had to use something like this:

```
var fontAwesomeIconCode: String? {
    let num = Int(strtoul(iconCode, nil, 16))
    if let scalar = UnicodeScalar(num) {
        return String(scalar)
    }
    return .none
}
```

**Comment by MatrixSenpai** [comment]
I was assuming in this case that what's returned is in Char format (i.e. `f290`). In that case, to match it against something in the library as it stands, you'd have to use my format. If that's not the case, as it seems from what you're doing, you can either use your solution, which will only convert to String, or you can do something more elaborate like conversion to Char/String with interpolation, then filtering. Either way, this doesn't seem like a common problem, and I'm not sure I really want to tackle this problem just yet. It does seem to be solved though, so I'm closing this issue.
That being said, I am going to put something on the project board to investigate other ways to initialize.

**Comment by beloso** [comment]
It’s definitely not a common problem. And definitively not worth to put a lot of effort into it. 

I just felt I had to ask the question. 
I got it working. I just wanted to know if there was a more straight forward way of doing it. 

Thank you for your inputs
