### ISSUE TITLE
Support coming for FontAwesome v5.13.1

### ISSUE THREAD

**Issue by MatrixSenpai** [thii/FontAwesome.swift#259]
Just letting everyone know, as of this moment I'm having some issues updating master because of a cli-swift issue.

Support is coming for the latest FontAwesome icons, as soon as I get this figured out. Thank you all for your patience

**Comment by perlguy99** [comment]
In case it helps, the script works with tools that are a bit older, I have Xcode 11.5 (11E608c) installed and it runs for me.  However, I'm trying to generate all of the Pro fonts and it seems to be missing the duotones and light fonts completely.  I turned on "Use Pro Fonts", do you have any other tips for generating ALL of the Pro fonts?  Thank you!

**Comment by perlguy99** [comment]
FYI, I got much further with the swift CLI script running by renaming `/Library/Developer/CommandLineTools` and then performing a `sudo xcode-select --install`.  Now the script compiles and tries to run, but I get a segmentation fault that I am trying to debug.

**Comment by MatrixSenpai** [comment]
Ensure that you've installed the submodule. There's a lot of force-unwrapping optionals in there, especially when it comes to decoding and reading the metadata file.

To install with pro fonts, you'll need to replace the FortAwesome/FontAwesome submodule with the FortAwesome/FontAwesome-Pro submodule, and change the path inside the script

**Comment by perlguy99** [comment]
I got the cli-swift file to run properly on one of the developer preview Macs!

**Comment by perlguy99** [comment]
Is duotone supported?  It looks like I only see 1 of the colors.

**Comment by MatrixSenpai** [comment]
duotone is not currently supported. I am debating how to show them, and whether to allow them in UILabels. Ligatures and SVGs are the two paths that seem readily available, but i'm not sure if either is the right choice. For now, I am closing all PRs related to them

**Comment by perlguy99** [comment]
I created a SwiftUI "demo" app for viewing the FontAwesome images...  [FontAwesome.SwiftUI.demo](https://github.com/perlguy99/FontAwesome.SwiftUI.demo)

**Comment by Kedar-27** [comment]
any ETA?

**Comment by MatrixSenpai** [comment]
Still working on a few things with the next version. Updated font support will be bundled in. If you need it in the meantime, you can manually add the library and update the font. You can still add it into your pod file, just ensure that it is pointed towards the local path and not the git repository. See more [here](https://guides.cocoapods.org/syntax/podfile.html#pod)

**Comment by hactar** [comment]
5.15.1 is the current version, hope that when you do find the time to upgrade, you can upgrade to the newest version :)

**Comment by MatrixSenpai** [comment]
Updating right now. Had to fix some shit with swift giving me the runaround. small changes to how things are done under the hood, but no changes to any of the core library or the release process

**Comment by MatrixSenpai** [comment]
07883a32d49dfc7bdedbeea115067b53dfbeeb43 pushed to master and CP, closing

**Comment by MatrixSenpai** [comment]
As a note, @thii I was having issues specifically with the `./codegen.swift` command. I was getting "This copy of libswiftCore.dylib requires an OS version prior to 10.14.4." I couldn't figure out what was causing it, and since I'm loathe to roll back to a previous version of Xcode, I just went ahead and added an executable target in the `Package.swift` and changed `./codegen.swift` -> `swift run tools`. `codegen.swift` got changed to `ROOT/tools/main.swift`

**Comment by thii** [comment]
Looks like a prolem with your machine's installed Swift runtime.

**Comment by MatrixSenpai** [comment]
It might very well be. I don't have a lot of space so I also only have one version of Xcode/swift installed atm. I'm working on getting CI to take care of bumps for us atm
