### ISSUE TITLE
Impossible to import the library in Xcode using CocoaPods

### ISSUE THREAD

**Issue by King-Wizard** [thii/FontAwesome.swift#26]
For more information, please consult the screenshots below:

<b>In Xcode imported pods list:</b>
![bug-cocoa-pods-library-import](https://cloud.githubusercontent.com/assets/5431357/8595193/6a0330c6-2648-11e5-82d5-e7578aa2b923.png)

<b>In Xcode source code:</b>
![import-not-found-in-xcode](https://cloud.githubusercontent.com/assets/5431357/8595197/6de305b8-2648-11e5-9a9c-7675590d3829.png)

<b>Podfile:</b>
![podfile](https://cloud.githubusercontent.com/assets/5431357/8595201/728bce6a-2648-11e5-925c-9c168f87e9b2.png)

Thank you in advance for keeping me updated on the fixing of this bug.

**Comment by thii** [comment]
It's FontAwesome_swift, not FontAwesome.swift. CocoaPods changes dot to underscore in framework name.

**Comment by King-Wizard** [comment]
Thank you for the answer, problem fixed.
