### ISSUE TITLE
FA.swift showing strange icons after update

### ISSUE THREAD

**Issue by christoph73** [thii/FontAwesome.swift#260]
Hi!

Maybe it is my foult, and I do not see a solution anywhere. I need advice, please.

After updating to XCode 11.6 and FA.swift 1.8.3 I just see strange Icons (basically question marks in boxes) instead of the correct icons.

Any thoughts? What am I doing wrong? Do I have to put my FA5 license anywhere?

I'd be greatful for help!

Regrads,
Christoph

**Comment by MatrixSenpai** [comment]
This happens when you are not loading the fonts correctly. Please ensure your fonts are in the `Copy Resources Phase` and you have filled out the `Fonts Provided By Application` key in your `Info.plist`

**Comment by christoph73** [comment]
I have done as adviced (see shots below). Anything else, that I might be missing? Are the otf-Files sufficient or do I need the ttf's in addition?

![1](https://user-images.githubusercontent.com/11836926/88222595-7f23bb00-cc66-11ea-80c2-8f34337dd669.png)
![2](https://user-images.githubusercontent.com/11836926/88222599-8054e800-cc66-11ea-84ef-e4185049f839.png)

Thanks for your help!

**Comment by MatrixSenpai** [comment]
Did you ensure `FontAwesomeConfig.useProIcons` is set to true in `AppDelegate.launch(withOptions:)`?

**Comment by christoph73** [comment]
No I did not, because I did noct stumble upon any documentation telling me so...
I now switched to "SwiftIcons" which worked with a minimum on migration effort right away. It seems a little more powerful aswell. Sorry, no offense! Keep the good work goin!
