### ISSUE TITLE
used to work now completely broken

### ISSUE THREAD

**Issue by smileatom** [thii/FontAwesome.swift#264]
I upgraded (I suppose since its been awhile since i originally put this in my app) 2016?  Now almost none of the icons load.  All are in the free package, I have squares with question marks all over my app.  What gives?

**Comment by MatrixSenpai** [comment]
I need some more information before I can do anything

- What font are you using? Are you loading the font yourself?
- Are you using storyboard or manually inserting text?
- Are you sure that the icon is available in the free font? Some icons have changed and may not be available since 2016

**Comment by smileatom** [comment]
Sorry man, icons not loading is just broken.  I had to replace about a hundred places in my app with another library.  I have no additional information on why your library broke.  You can close this.   Im not waiting on anything.
