### ISSUE TITLE
this is wired

### ISSUE THREAD

**Issue by lostpupil** [thii/FontAwesome.swift#3]
I am trying to follow readme to get fontawesome workink, and I set it right at the first time, then I get the icon correctly, but I don't know why it doesn't working now. after I launching the program, I kept get this error.
![image](https://cloud.githubusercontent.com/assets/2015695/5800673/caec06c2-a01c-11e4-8e80-951397789b76.png)
![image](https://cloud.githubusercontent.com/assets/2015695/5800677/db551cd8-a01c-11e4-9ba9-b2a97c6b98b0.png)
I just want to say, I have got the icon correctly but why it doesn't work now?

**Comment by thii** [comment]
@lostpupil Can you test with the version 0.2.0?

**Comment by lostpupil** [comment]
I followed your readme but always can not render the font on sim or real iphone. 
I will test with 0.2.0.
Thx for your reply.

**Comment by thii** [comment]
@lostpupil From version 0.2.0 the font will be loaded dynamically so you don't need to edit your project's plist file anymore. Just add the swift file and OTF file to your project and you're done.

**Comment by lostpupil** [comment]
![image](https://cloud.githubusercontent.com/assets/2015695/5871725/af818f08-a31c-11e4-8d1b-163099a2af9a.png)

![image](https://cloud.githubusercontent.com/assets/2015695/5871710/831ffde6-a31c-11e4-9db7-6b6c99ff9284.png)

**Comment by thii** [comment]
@lostpupil Can you check `FontAwesome.otf`'s target membership?

**Comment by lostpupil** [comment]
great it works! thx for your patience!

**Comment by thii** [comment]
👍
