### ISSUE TITLE
Swift 2

### ISSUE THREAD

**Issue by mattgabor** [thii/FontAwesome.swift#31]
Is there any plans to update this for Swift 2.0? I get errors when trying to compile in Xcode 7

**Comment by kronik** [comment]
Found and issue related with recent change of "advance' signature (in fontAwesomeIconWithName). Could you update your source to support Index.advancedBy? 

Thanks.

**Comment by japarrado** [comment]
same problem detected, any plans for update to swift2.0?
Thx

**Comment by ryanriley** [comment]
Line 72 in FontAwesome.swift needs to be:

return name.rawValue.substringToIndex(name.rawValue.startIndex.advancedBy(1))

**Comment by abury** [comment]
There is already a fix for this in the 'swift-2.0' branch. I'm not sure why it hasn't been merged into master yet but until then you can set your podfile to:

```
pod 'FontAwesome.swift', :git => 'https://github.com/thii/FontAwesome.swift.git', :branch => 'swift-2.0'
```

**Comment by japarrado** [comment]
When i use this lib for display awesome, example: "self.title = String.fontAwesomeIconWithName(.Gift)". I get the next result: 
<img width="65" alt="captura de pantalla 2015-09-21 a las 12 55 03" src="https://cloud.githubusercontent.com/assets/6688600/9990261/2e8fea14-6060-11e5-8460-8b5e2e2a6c99.png">

Any idea?

**Comment by Daemon-Devarshi** [comment]
@abury thanks .. even I tried to submit the pull request - https://github.com/thii/FontAwesome.swift/pull/39#partial-pull-merging

**Comment by thii** [comment]
Sorry for the long wait. It has just been updated for Swift 2.0.

**Comment by abury** [comment]
Thanks @thii ! Love your work! :+1:

**Comment by sagits** [comment]
Hi, i'm new to swift/ios development. Can you provide a solution for cocoapod to load the swift 1.0 last commit (i'm using xcode 6)? Thank you in advance.

**Comment by thii** [comment]
@sagits You can specify version in your Podfile as below:
`pod 'FontAwesome.swift', '~> 0.5.0'`
