### ISSUE TITLE
dispatch_once in fontAwesomeIconWithName is not effective / token is not static

### ISSUE THREAD

**Issue by bluenose01** [thii/FontAwesome.swift#4]
The "dispatch_once" call inside of "fontAwesomeIconWithName()" is not effective.  The icons table is setup every time the function is called because the 'token' var itself is not static, which can result in poor performance if used frequently.

```
public extension String {
  public static func fontAwesomeIconWithName(name: String) -> String {
    var icons: [String: String]?
    var token: dispatch_once_t = 0    //  This is reset to 0 on every call, so 'dispatch_once' does nothing
    
    dispatch_once(&token) {
      icons = [
        "fa-adjust": "\u{f042}",...
```

If you debug this code (xcode debugger or just print), you will see that "token" is always 0 when the function is invoked.  When using this function a lot, the performance was degraded surprisingly.  

If you move the token / dictionary out to static symbols, the performance improves to expected levels.

**Comment by prrrnd** [comment]
I agree, discovered this too when I was using different icons in each cell of a UITableView.

**Comment by thii** [comment]
Fixed in latest release.
