### ISSUE TITLE
don't show icon in swift2

### ISSUE THREAD

**Issue by japarrado** [thii/FontAwesome.swift#45]
i have v0.6 and import FontAwesome_swift or import FontAwesome

When i use this lib for show icon: 
self.title = String.fontAwesomeIconWithName(.Android)
i have the next result: 
<img width="320" alt="captura de pantalla 2015-09-25 a las 11 34 51" src="https://cloud.githubusercontent.com/assets/6688600/10097459/7644c7dc-6379-11e5-9070-f5937d57730e.png">

Any idea?

**Comment by thii** [comment]
Did you set the FontAwesome font for the navigation bar title?

**Comment by japarrado** [comment]
yes!! i need set FontAwesome Font ;)

Thanks
