### ISSUE TITLE
dyld: library not loaded: @rpath/libswiftSecurity.dylib crash

### ISSUE THREAD

**Issue by mvpbld** [thii/FontAwesome.swift#54]
I have a problem with your library.
This is the Xcode's console:

dyld: Library not loaded: @rpath/libswiftSecurity.dylib
  Referenced from: /private/var/mobile/Containers/Bundle/Application/524AE979-D123-455E-83CC-DB96E01BC348/FoodApp.app/Frameworks/FontAwesome_swift.framework/FontAwesome_swift
  Reason: image not found

**Comment by thii** [comment]
Probably there was a problem with previous version of Xcode or the Swift compiler. Having no problem with Xcode 7.2 so I'm closing this now.
