### ISSUE TITLE
need fontAwesomeIconWithUnicode

### ISSUE THREAD

**Issue by djdance** [thii/FontAwesome.swift#56]
For some reason my php sends me article icons got from *fontawesome.io* lists
**f0f6** (this is plain string, not Unicode character)

to convert it to **\u{f0f6}"** (singleUnicode  character) I have to do:

```
let t="f0f6" //got this icon from server
let c=Int(strtoul(t, nil, 16))
let ch=Character(UnicodeScalar(c))
var s=""
s.append(ch)
iconLabel.text = s
```

I think we need func doing this, a kind of *String.fontAwesomeIconWithUnicode*

**Comment by thii** [comment]
So you need to make your php sends you the icon name instead of the Unicode string. Or if you could write the `String.fontAwesomeIconWithUnicode` function it would be awesome.
