### ISSUE TITLE
Does not work with Carthage at version 0.7.0

### ISSUE THREAD

**Issue by 0x686169** [thii/FontAwesome.swift#59]
![simulator screen shot jan 27 2016 10 08 55 pm](https://cloud.githubusercontent.com/assets/1132303/12617544/b1f764bc-c542-11e5-8e3b-e6b56345d73b.png)

I try use your lib with carthage :), unfortunately the awesome texts always wrong
my codes
self.navigationItem.rightBarButtonItem = UIBarButtonItem(title: String.fontAwesomeIconWithName( FontAwesome.PlusSquare), style: .Plain, target: self, action: "createNote")
        self.title = String.fontAwesomeIconWithName(.Github)

Please give me an advise to solve this.

Thanks,

**Comment by thii** [comment]
You didn't set the font.

Here is an example on how to do it:

```swift
self.navigationItem.rightBarButtonItem = UIBarButtonItem(title: String.fontAwesomeIconWithName( FontAwesome.PlusSquare), style: .Plain, target: self, action: "createNote")
self.title = String.fontAwesomeIconWithName(.Github)

let attributes = [NSFontAttributeName: UIFont.fontAwesomeOfSize(20)] as Dictionary!
self.navigationController?.navigationBar.titleTextAttributes = attributes
self.navigationItem.rightBarButtonItem!.setTitleTextAttributes(attributes, forState: .Normal)
```
