### ISSUE TITLE
Add support to UIButton

### ISSUE THREAD

**Issue by JV17** [thii/FontAwesome.swift#6]
I have tried this framework to work with UIButton but I haven't been able to find a way around it to make it work.. Not sure if it supports UIButton yet but if it does it might be great to have an example in the readme file.

Thanks in advance!

**Comment by thehellsoul** [comment]
if you use Interface Builder, i can suggest a way:
1/ Select FontAwesome as custom font from Interface Builder for your UIButton title.
2/ Copy the character you want from FontAwesome cheatsheet and paste it to UIButton title field.

**Comment by JV17** [comment]
@thehellsoul thanks for the suggestion but I am not using interface builder.. I think, I will try to do added to the framework whenever I get some free time.. Just basically to be able to creates images, buttons or whatever..

**Comment by harlanhaskins** [comment]
`UIButton` has a `titleLabel` property which is a `UILabel`.

Just use the example from the README except substitute `myLabel` for `myButton.titleLabel`.

**Comment by k-yamada** [comment]
This is a sample code.

~~~
@IBOutlet weak var searchButton: UIButton!

override func viewDidLoad() {
  super.viewDidLoad()
  searchButton.titleLabel!.font = UIFont.fontAwesomeOfSize(18)
  searchButton.setTitle(String.fontAwesomeIconWithName(FontAwesome.Search), forState: UIControlState.Normal)
}
~~~

**Comment by thii** [comment]
@JV17 Sorry for late reply. Please see sample codes in the Demo project.
