### ISSUE TITLE
Generic solution for other fonts

### ISSUE THREAD

**Issue by marekmatula** [thii/FontAwesome.swift#61]
I'm using vaadin icons in my java project.
https://vaadin.com/font-icons

Also many other free fonts exist:
http://speckyboy.com/2014/05/14/more-free-icon-fonts/

It should be nice to have some generic solution for font icons in swift.
Share common methods. Easy add new font. etc

Have you any idea how to do it?

**Comment by thii** [comment]
It is impossible to do this since we need to store all icon names in enum in order to convert the icon name to the correct icon character/string. You can make a similar library for a specific font though.
