### ISSUE TITLE
Spinner support

### ISSUE THREAD

**Issue by luisgizirian** [thii/FontAwesome.swift#63]
@thii, any ideas if it's possible to use the spinners?

**Comment by thii** [comment]
@luisgizirian Can you please explain more clearly?

**Comment by luisgizirian** [comment]
Of course @thii. Sorry about that.

Font awesome, has the ability to display [spinner icons](https://fortawesome.github.io/Font-Awesome/examples/#animated) (those used for "Loading..." kinda screens & overlays).  I think these is some CSS trickery on top of icons. Are these kind of animations also ported inside this swift library?

Hope I made myself clear this time! Thanks!

**Comment by thii** [comment]
@luisgizirian You'll probably have to use UIAnimation to rotate the container  (UILabel...) of the icon you want to spin. I'll have to look into this to see if we can have spinner support inside this library.

**Comment by DavidGagne** [comment]
I, too, would appreciate this feature.
