### ISSUE TITLE
Carthage cannot from current master

### ISSUE THREAD

**Issue by ryan-blunden** [thii/FontAwesome.swift#66]
Xcode:  7.2.1, Build version 7C1002
Carthage: 0.15.1

Contents of `Cartfile: github "thii/FontAwesome.swift"`

```
*** Building scheme "FontAwesome" in FontAwesome.xcodeproj
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64 /Users/rb/Projects/AFTR/aftr-ios/AFTR/Carthage/Checkouts/FontAwesome.swift/FontAwesomeTests/FontAwesomeTests.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
/Users/rb/Projects/AFTR/aftr-ios/AFTR/Carthage/Checkouts/FontAwesome.swift/FontAwesomeTests/FontAwesomeTests.swift:25:18: error: module 'FontAwesome' was not compiled for testing
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64 /Users/rb/Projects/AFTR/aftr-ios/AFTR/Carthage/Checkouts/FontAwesome.swift/FontAwesomeTests/FontAwesomeTests.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

**Comment by thii** [comment]
Please use v0.7.0 when I'm investigating this.

`github "thii/FontAwesome.swift" "0.7.0"`

**Comment by awesomeswift** [comment]
thanks @thii 
more infos:

The following build commands failed:
	CompileSwift normal arm64 /Users/awesomeswift/Refactor/awesomeswift/awesomeswift/Carthage/Checkouts/FontAwesome.swift/FontAwesomeTests/FontAwesomeTests.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
/Users/awesomeswift/Refactor/awesomeswift/awesomeswift/Carthage/Checkouts/FontAwesome.swift/FontAwesomeTests/FontAwesomeTests.swift:25:18: error: module 'FontAwesome' was not compiled for testing
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64 /Users/awesomeswift/Refactor/awesomeswift/awesomeswift/Carthage/Checkouts/FontAwesome.swift/FontAwesomeTests/FontAwesomeTests.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by wuaschtikus** [comment]
I am experiencing this too. With 0.7.0 & 0.7.1 with Xcode 7.3

**Comment by ReedD** [comment]
:+1:

**Comment by leizard** [comment]
I have the same issue with `github "thii/FontAwesome.swift" >= 0.4.1` . While Cocoapod also not work, is manually coping files is the only way to install ?

**Comment by thii** [comment]
@leizard `github "thii/FontAwesome.swift" "0.7.0"` should work.

**Comment by leizard** [comment]
Hi bạn @thii :D ,
updated cocoapods to 1.0.0 beta 8 and I could use cocoa to install normally.
Thank you for awesome library.

**Comment by Padarom** [comment]
Could be related (Carthage 0.15.1):

```
$ carthage update --platform iOS --no-use-binaries
# ....
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
A shell task failed with exit code 66:
xcodebuild: error: Scheme FontAwesome-watchOS is not currently configured for the build action.
```

Even though I'm using `github "thii/FontAwesome.swift" "0.7.0"` as @thii suggested.
