### ISSUE TITLE
Question mark instead of icon

### ISSUE THREAD

**Issue by PLozinski** [thii/FontAwesome.swift#67]
Hi, I have small problem. After installation FontAwesome by using CocoaPoads I have seen question marks in rectangle instead of icon. I don't know why ... ?

**Comment by mbenjamin618** [comment]
I don't know if this is your issue but if you don't add the label.font = UIFont.fontAwesomeOfSize it shows a questions mark. Hope this helps!

**Comment by PLozinski** [comment]
Thanks for answer. I solved this problem by update Xcode to 7.3 version :+1:
