### ISSUE TITLE
cocoapods 1.0.0 crash

### ISSUE THREAD

**Issue by DKalachniuk** [thii/FontAwesome.swift#71]
Hi, since I updated to cocopods 1.0.0
I receive this crash

<img width="647" alt="screen shot 2016-05-16 at 23 20 23" src="https://cloud.githubusercontent.com/assets/2156751/15304305/dfd7ac5e-1bbc-11e6-8c3b-54e47ff40f17.png">

Please advice

this is my podfile

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'MyApp' do
pod 'ECSlidingViewController', '~> 2.0.3'
pod 'AFNetworking', '~> 2.5'
pod 'PNChart', '~> 0.7.1'
pod 'FontAwesome.swift'
end

**Comment by thii** [comment]
I couldn't replicate this.

**Comment by CAPIStkidd** [comment]
I'm getting this too. For what it's worth I'm getting this on a project which was previously using CocoaPods 0.39 or whatever the last non-beta one before 1.0 was, then when I upgrade to 1.0 I get this issue. Happens on FontAwesome.swift 0.7.1 and 0.7.3.

**Comment by thii** [comment]
@DKalachniuk @CAPIStkidd I could not replicate this. Can you send in a sample project that replicates this crash?

**Comment by CAPIStkidd** [comment]
I can't send the main project I was working with for obvious reasons, but I just created a gutted version of it to recreate the issue to send... except the issue doesn't show up in the gutted version. 

I'll see if I can diff the two and figure out anything good but yeah, this is weird.

**Comment by thii** [comment]
@CAPIStkidd So there might be something wrong with your project's settings, not with this library. If you could make the gutted version crash, I'd be happy to help.

You might want to try removing this from your Podfile, `pod install`, re-add this, `pod install` again to see if it works.

**Comment by CAPIStkidd** [comment]
And now my main project doesn't have the issue anymore either (as in, after doing an upgrade with CocoaPods 1.0 it no longer has the crash where it can't find the otf/bundle). 

One thing to note is that I wasn't on board with the changes to the podfile syntax (everything has to be in a target) so I did that, maybe that had something to do with it.

http://stackoverflow.com/questions/34556991/pod-install-displaying-error-in-cocoapods-version-1-0-0-beta-1

**Comment by thii** [comment]
Correct! From [CocoaPods 1.0](http://blog.cocoapods.org/CocoaPods-1.0-Migration-Guide/),
> You now have to define targets. Previously there was an available implicit target.

**Comment by kush786** [comment]
I have set the target then also I am getting the same issue!
