### ISSUE TITLE
Icon as UIView

### ISSUE THREAD

**Issue by DavidGagne** [thii/FontAwesome.swift#72]
I'm trying to set the disclosure indicator on a tableview to the FontAwesome CaretRight icon, which would be perfect for my app. Unfortunately I can't seem to do that because the .accessoryView property of the table cell must be of type UIView.

It would be great if this was an option in this pod. Thanks for considering it.

**Comment by thii** [comment]
```swift
let image = UIImage.fontAwesomeIconWithName(.CaretRight, textColor: .lightGrayColor(), size: CGSizeMake(30, 30))
let imageView = UIImageView(image: image)
cell.accessoryView = imageView
```

**Comment by DavidGagne** [comment]
Excellent! Thanks!
