### ISSUE TITLE
Swift 2.3 Syntax issues

### ISSUE THREAD

**Issue by otymartin** [thii/FontAwesome.swift#76]
```swift
FontAwesome.swift:120:49: Value of optional type 'CGDataProvider?' not unwrapped; did you mean to use '!' or '?'?

FontAwesome/FontAwesome.swift:98:16: Value of optional type 'UIImage?' not unwrapped; did you mean to use '!' or '?'?
```

**Comment by zhihuitang** [comment]
why it was closed? I am experiencing the exact problem, have you guys fixed it? thanks

**Comment by schystz** [comment]
Was experiencing this too when running the project on Xcode 8.2.1 with use swift legacy version enabled, it works fine in Xcode 7 though.

**Comment by otymartin** [comment]
@schystz no i just dropped the library.

**Comment by schystz** [comment]
Oh okay. I was able to make it work by pointing the podfile to the `swift-2.3` branch
