### ISSUE TITLE
fatal error 

### ISSUE THREAD

**Issue by J-Arji** [thii/FontAwesome.swift#77]
hi 
when i ruling program  app crash
in line           `  fontURL = bundle.URLForResource(name, withExtension: "otf", subdirectory: "FontAwesome.swift.bundle")!`
`error : fatal error: unexpectedly found nil while unwrapping an Optional value
`

can you help me ?

**Comment by rocket-enterprise** [comment]
I have the same problem since ill updated to Cocoapods 1.0. Already tried:

removing cache, installing pods again, using new pod layout from 1.0. Removing pods from existing project and install everything new.

But with no success. But: When ill create a new project, everything works fine. 

Thats weird (and there is another question here with the same problem)

**Comment by piyushkantm** [comment]
having same problem after updating to pods 1.0..

**Comment by piyushkantm** [comment]
having same problem after updating to Cocoapods 1.0.. Any fix on this yet?

**Comment by cerebroo** [comment]
Cleaning the build folder ( Cmd + Shift + Alt + K ), fixed it for me.

**Comment by marsman12019** [comment]
I'm having the exact same issue.

**Comment by piyushkantm** [comment]
@marsman12019 
Do what @cerebroo said, clean the build folder and it will work

**Comment by marsman12019** [comment]
Cleaning the build folder didn't work for me, but reverting to a previous commit did.

**Comment by Mike1707** [comment]
For me it does not work and I have the same error. I also tried different builds with cocoapods (from 0.6.3 to 0.8.0).

**Comment by chjk** [comment]
fontURL = bundle.URLForResource(name, withExtension: "otf", subdirectory: "FontAwesome.swift.bundle")!

Cocoapods 1.0.1
**it will not work on the simulator，but it works well on my iphone.**

**so...**
Manually
Drag and drop FontAwesome.otf and all Swift files into your project
