### ISSUE TITLE
Swift 3.0 compatibility errors

### ISSUE THREAD

**Issue by ecnepsnai** [thii/FontAwesome.swift#78]
- FontAwesome.swift:37:36: `dispatch_once_t` is unavailable in Swift: Use lazily initialized globals instead
 - FontAwesome.swift:41:19: `fontNamesForFamilyName` has been renamed to `fontNames(forFamilyName:)`
 - FontAwesome.swift:59:21: Value of type `String` has no member `substringToIndex`
 - FontAwesome.swift:71:45: Missing argument label `name:` in call
 - FontAwesome.swift:85:136: `clearColor()` has been renamed to `clear()`
 - FontAwesome.swift:87:47: `Center` has been renamed to `center`
 - FontAwesome.swift:93:32: `NSAttributedString` has been renamed to `AttributedString`
 - FontAwesome.swift:98:16: Value of optional type `UIImage?` not unwrapped; did you mean to use `!` or `?`?
 - FontAwesome.swift:106:22: `NSBundle` has been renamed to `Bundle`
 - FontAwesome.swift:117:42: `NSURL` is not implicitly convertible to `URL`; did you mean to use `as` to explicitly convert?
 - FontAwesome.swift:124:35: `CFStringRef` has been renamed to `CFString`

**Comment by thii** [comment]
Could you make a PR for those?

**Comment by ecnepsnai** [comment]
Sure, should do it in a separate branch for now until Swift 3.0 is released this Sept.

**Comment by ecnepsnai** [comment]
Hey @thii there's one thing I need your help with:

Swift deprecated dispatch_once and wants you to use lazy vars instead, can you take a look [at this function](https://github.com/ecnepsnai/FontAwesome.swift/blob/2a257083e9215e222a7a0a5f52823c44001eaf16/FontAwesome/FontAwesome.swift#L42) and do you have any ideas on how to refactor it to support lazy vars?

**Comment by Tulleb** [comment]
Hi guys, I would need this branch too to work along with CocoaPods.

Thanks @ecnepsnai for the help. Sadly I don't know about dispatch_once, can't really help out here.
Do you have any news about it @thii?

**Comment by Tulleb** [comment]
Any updates guys...? @ecnepsnai @thii?
