### ISSUE TITLE
Add FontAwesomeView

### ISSUE THREAD

**Issue by antonyalkmim** [thii/FontAwesome.swift#79]
I implemented a view that can be used directly in the storyboard and set which icon to use.

![captura de tela 2016-06-28 as 04 59 33](https://cloud.githubusercontent.com/assets/6514332/16408056/33db8f40-3ced-11e6-9967-b1f479fd088b.png)

Let me know if you'd like me to submit a PullRequest.

**Comment by thii** [comment]
Cool! I would love to see that.

**Comment by robcas3** [comment]
I can't see FontAwesomeView in cocoapods yet, could you update?

**Comment by antonyalkmim** [comment]
@thii can you update the podspec?

**Comment by lhzbxx** [comment]
The work is great!
However, I can not use it in fact. I can not set a UIView as Font Awesome View.
I'm sure that I'm using the newest version (0.7.3). So, what's the problem?
Thanks!

**Comment by thii** [comment]
Just updated the podspec to 0.8.0.
