### ISSUE TITLE
3 dots instead of icon

### ISSUE THREAD

**Issue by Rauleinstein** [thii/FontAwesome.swift#81]
Hi, I'm experience some problems where I see 3 dots as ". . ." instead of the actual icon. Any suggestion on where might be the problem?

**Comment by antonyalkmim** [comment]
Are you using UILabel? Try change width or height. Probably the UILabel is truncating your string icon.
If not succes, try using UIImage instead UILabel.

**Comment by Rauleinstein** [comment]
That was the problem I've put the font size too big and some icons were truncating, putting the size font smaller solved my problem. 
THANKS!
Some heroes doesn't wear capes.

**Comment by ServicePal** [comment]
Just FYI. This will also happen if you have a user who is setting "Larger Text" in Accessibility settings.

**Comment by Rauleinstein** [comment]
Thanks for the info, I haven't thought about this. I will give it a try and see what happens in my app
