### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by z3t0** [thii/FontAwesome.swift#92]
Is there anyway to get this to work with OS X?

**Comment by msamoylov** [comment]
+1

**Comment by OliverZiegler** [comment]
I started implementing this [here](https://github.com/OliverZiegler/FontAwesome.swift/tree/osx) but got some issues.

Icons get rendered only 2/3 into the images and labels and rest of icon is cut of at bottom.
Check out the macOS Demo.

If someone has any ideas PRs are welcome.

**Comment by wess** [comment]
+1

**Comment by OliverZiegler** [comment]
Check out current state.
Currently working with NSFont and NSImage.

Also try via Podfile:
`pod 'FontAwesome.swift', :git => 'https://github.com/OliverZiegler/FontAwesome.swift/tree/osx', :branch => 'osx'`

Would like to get feedback.

**Comment by Ivorforce** [comment]
I get a bunch of Swift update errors:

Pods/FontAwesome.swift/FontAwesome-macOS/NSImage+FontAwesome.swift:46:110: 'NSFontAttributeName' has been renamed to 'NSAttributedStringKey.font'

Pods/AppKit.NSFontAttributeName:4:12: 'NSFontAttributeName' was obsoleted in Swift 3

Pods/FontAwesome.swift/FontAwesome-macOS/NSImage+FontAwesome.swift:46:167: 'NSForegroundColorAttributeName' has been renamed to 'NSAttributedStringKey.foregroundColor'

Pods/AppKit.NSForegroundColorAttributeName:3:12: 'NSForegroundColorAttributeName' was obsoleted in Swift 3

Pods/FontAwesome.swift/FontAwesome-macOS/NSImage+FontAwesome.swift:46:210: 'NSBackgroundColorAttributeName' has been renamed to 'NSAttributedStringKey.backgroundColor'

Pods/AppKit.NSBackgroundColorAttributeName:3:12: 'NSBackgroundColorAttributeName' was obsoleted in Swift 3

Pods/FontAwesome.swift/FontAwesome-macOS/NSImage+FontAwesome.swift:46:259: 'NSParagraphStyleAttributeName' has been renamed to 'NSAttributedStringKey.paragraphStyle'

Pods/AppKit.NSParagraphStyleAttributeName:3:12: 'NSParagraphStyleAttributeName' was obsoleted in Swift 3


It would also be very nice to have Carthage support for the osx version =)

**Comment by relisiuol** [comment]
https://github.com/qvacua/CocoaFontAwesome
