### ISSUE TITLE
Swift 3.0 branch - build issue

### ISSUE THREAD

**Issue by mtissington** [thii/FontAwesome.swift#94]
In my pod file I have 
  pod 'FontAwesome.swift', :git => 'https://github.com/thii/FontAwesome.swift.git', :branch => 'swift-3.0'

I'm getting the following two errors when trying to build in func setupViews

1) Center has been renamed to center

in layoutSubViews

2) CGRectMake in unavailable in Swift

**Comment by Tulleb** [comment]
@mtissington I don't know what @thii has in mind currently.
He was not answering for months and now he just closed every PR we submitted to fix Swift 3.0 compatibility without saying why...

You can still add this line to your Podfile if you need it:
`pod 'FontAwesome.swift', :git => 'https://github.com/Tulleb/FontAwesome.swift.git', :branch => 'swift3'`

**Comment by james-ff** [comment]
Having problems building this framework (on the swift-3.0 branch) with my project in Xcode 8, Swift 3.0.

**Comment by thii** [comment]
Please use 
`pod 'FontAwesome.swift', :git => 'https://github.com/thii/FontAwesome.swift.git', :branch => 'master'`

Due to an issue in CocoaPods, I haven't pushed to the master repo yet.

**Comment by Tulleb** [comment]
Working but just one small issue left when using with CocoaPods.

Issue: #97 
PR: #98
