### ISSUE TITLE
Show error after update xcode

### ISSUE THREAD

**Issue by zahedul** [thii/FontAwesome.swift#99]
after updating xcode then show following error
<img width="1280" alt="screen shot 2016-09-16 at 4 33 14 am" src="https://cloud.githubusercontent.com/assets/1929044/18569779/b2f62dcc-7bc6-11e6-9582-d80bbfd3cea6.png">

**Comment by thii** [comment]
Which version are you using?

**Comment by zahedul** [comment]
issue solved after adding
`pod 'FontAwesome.swift', :git => 'https://github.com/thii/FontAwesome.swift', :branch => 'swift-2.3'`

thanks
